In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time

In [18]:
options = webdriver.ChromeOptions()
options.add_argument("--headless")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

In [4]:
KEYWORDS = [
    "lpg shortage",
    "gas shortage",
    "gas supply shortage",
    "cooking gas crisis",
    "hotel",
    "restaurant",
    "eatery",
    "hospitality"
]

In [26]:
import requests
from bs4 import BeautifulSoup

def get_article_links():
    url = "https://news.google.com/rss/search?q=LPG+shortage+restaurant+hotel+gas+supply"
    
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "xml")

    links = []
    for item in soup.find_all("item"):
        links.append(item.link.text)

    return links

In [27]:
l=get_article_links()

In [30]:
print(len(l))

100

In [22]:
from newspaper import Article

def extract_article(url):
    try:
        article = Article(url)
        article.download()
        article.parse()
        return article.text
    except Exception as e:
        print(f"Failed: {url}")
        return None

In [23]:
def is_relevant(text):
    text_lower = text.lower()
    return any(keyword in text_lower for keyword in KEYWORDS)

In [33]:
def get_relevant_articles():
    links = get_article_links()
    results = []

    for url in links:
        driver.get(url)
        time.sleep(1)  # wait for redirects + page load

        # optional: get final resolved URL
        final_url = driver.current_url
        print(f"Processing: {final_url}")
        text = extract_article(final_url)

        if text and is_relevant(text):
            results.append({
                "url": final_url,
                "text": text  # preview
            })

    return results

In [34]:
articles = get_relevant_articles()

Processing: https://www.msn.com/en-in/news/world/lpg-shortage-hits-restaurants-customers-report-extra-gas-supply-issue-fees/ar-AA1YymhL?apiversion=v2&domshim=1&noservercache=1&noservertelemetry=1&batchservertelemetry=1&renderwebcomponents=1&wcseo=1
Processing: https://indianexpress.com/article/cities/bangalore/as-bengaluru-hotels-cut-menus-amid-lpg-crisis-how-this-restaurant-is-using-8-tonnes-of-city-waste-to-take-on-more-cooking-10598014/
Processing: https://www.bhaskarenglish.in/local/mp/news/mp-lpg-shortage-hotels-restaurants-hit-additional-chief-secretary-rashmi-shami-137506896.html
Processing: https://thenewsmill.com/2026/03/commercial-lpg-shortage-disrupts-hotels-as-government-prioritises-domestic-supply-amid-west-asia-conflict/
Processing: https://www.thegoan.net/goa-news/%EF%BB%BFlpg-shortage-pushes-south-goa-hotels-to-brink-owners-seek-cms-urgent-intervention/145485.html
Processing: https://economictimes.indiatimes.com/industry/energy/oil-gas/lpg-crisis-restaurant-body-seeks-relief-from-maha-government-amid-gas-shortage/articleshow/129647056.cms?from=mdr
Processing: https://www.indiatvnews.com/madhya-pradesh/mp-govt-allocates-9-lpg-to-hotels-restaurants-7-to-dhabas-in-big-relief-amid-commercial-lpg-shortage-2026-03-24-1034832
Processing: https://www.thehindu.com/news/national/karnataka/lpg-shortage-about-20-of-hotel-industry-needs-will-be-met-daily-with-immediate-effect-announces-karnataka-minister/article70775152.ece
Processing: https://www.msn.com/en-in/news/world/commercial-lpg-shortage-government-forms-panel-to-address-supply-crunch/ar-AA1XSP6u?gemSnapshotKey=GMD566ED7D-snapshot-22&uxmode=ruby
Processing: https://economictimes.indiatimes.com/industry/services/hotels-/-restaurants/lpg-shortage-shuts-mumbai-restaurants-as-20-kitchens-run-out-of-cooking-gas/articleshow/129444114.cms?from=mdr
Failed: https://economictimes.indiatimes.com/industry/services/hotels-/-restaurants/lpg-shortage-shuts-mumbai-restaurants-as-20-kitchens-run-out-of-cooking-gas/articleshow/129444114.cms?from=mdr
Processing: https://news.google.com/rss/articles/CBMi7wFBVV95cUxNQjVzWEFidk53NU9BX3JRUWpmX0JVaTd1STBWMWhieGRXd2NpdzB6R0V2VWVFV2hPWERFNDdsNThwa2lHQzFhTTJkNmF6TFFEaGtYb1dUaDZlQUdWNEhmNTlILV9ZbXZzS0thckNhU29vSGFaVnVaWkRqUWZVaWZZTENwRkVVTGkxdHNpNEJzNGd0RUJRdHMxWmdETG5SNEwyLUI5bHlYRU82eDE2c1JzWjh5bDVXTkZ3UFhRNlVCdUlBbGNlSnRpNmtoWE9DUkd2U2g2ajdvTjJPUVpad1NqeTFyY2c5eXJyVWVqaGNHNNIB9gFBVV95cUxPRGxBcXVfNFVEXzRfZUFTeWp6RkJtdmVkQUhKT1JRZGt6RmhIdXRKdkdqVmZsdnBkejBXTXB5d190ME12ZTNpZkFFVDFDcHVPejlYem1aU2ppODNXOXF4Zi1QSVpzSnF4cVJOaWl2MHJVT3ZqWGxBX3E2X19JbUhXQndBUVVtYVc2aFdUSnV4Y3A3eVpreUFkU05ibFY5RUVxQ1kyV1h6SkZFWG42bHdIQTNFM3FnRGN4dTdJb09zaWNwcHZFckpxOE9uUFJpUDZSRzRkVGFQWHlDTVNESmN5VlIwZUEyMl9SRkNIWVJERm1MZlQ0TFE?oc=5
Processing: https://www.thehindu.com/news/national/indian-hotels-grapple-with-gas-shortage-as-west-asia-conflict-prolongs/article70726061.ece
Processing: https://www.thehindu.com/news/national/maharashtra/commercial-lpg-quota-in-maharashtra-raised-by-20-on-centres-directive/article70772839.ece
Processing: https://www.thehindu.com/news/cities/Hyderabad/restaurateurs-in-hyderabad-face-concerns-over-commercial-lpg-supply-city-is-home-to-over-74000-restaurants/article70725637.ece
Processing: https://english.dainikjagranmpcg.com/states/madhya-pradesh/mp-commercial-lpg-supply-resumes-after-13-day-crisis/article-15879
Processing: https://www.thehindu.com/news/national/odisha/odisha-hotel-and-restaurant-association-flags-lpg-cylinder-shortage-issue/article70727224.ece
Processing: https://www.bhaskarenglish.in/amp/local/mp/news/mp-lpg-supply-hotels-restaurants-vendors-order-issued-137515516.html
Processing: https://upstox.com/news/business-news/latest-updates/lpg-shortage-hits-hotels-restaurants-how-is-the-govt-responding/article-190445/
Processing: https://hospitality.economictimes.indiatimes.com/news/operations/food-and-beverages/lpg-shortage-squeezes-food-industry-as-black-market-thrives-and-cylinder-prices-soar/129713438
Processing: https://timesofindia.indiatimes.com/city/mumbai/lpg-shortage-shuts-eateries-across-mumbai-up-to-20-hotels-restaurants-hit-says-industry-body/articleshow/129413549.cms
Processing: https://www.hotelierindia.com/operations/lpg-hotels-restaurants
Failed: https://www.hotelierindia.com/operations/lpg-hotels-restaurants
Processing: https://ommcomnews.com/odisha-news/food-supplies-minister-assures-adequate-lpg-stock-urges-calm-amid-gas-shortage/
Processing: https://www.thehindu.com/news/cities/mumbai/lpg-shortage-shuts-20-of-mumbai-eateries-industry-warns-of-wider-closures/article70726058.ece
Processing: https://www.thehindu.com/news/cities/bangalore/lpg-crisis-restaurants-in-bengaluru-likely-to-shut-services-as-lpg-supply-remains-uncertain/article70727551.ece
Processing: https://thefederal.com/category/business/lpg-shortage-hits-hotels-tamil-nadu-karnataka-bengaluru-menus-cut-233585
Processing: https://timesofindia.indiatimes.com/city/mumbai/lpg-shortage-20-commercial-piped-gas-cut-hits-hotels-food-chains-in-mumbai/articleshow/129587048.cms
Processing: https://www.thehindu.com/news/cities/Hyderabad/lpg-shortage-begins-to-hit-hyderabad-restaurants-as-menus-shrink-an-outlet-shut-for-friday/article70738442.ece
Processing: https://www.newindianexpress.com/states/kerala/2026/Mar/12/lpg-shortage-70-of-kerala-restaurants-to-shut-by-weekend
Processing: https://economictimes.indiatimes.com/industry/energy/oil-gas/shortage-of-commercial-lpg-could-hit-50-of-hotels-and-restuarants-in-mumbai-industry-bodies/articleshow/129385445.cms?from=mdr
Processing: https://www.thehindu.com/news/national/kerala/lgp-shortage-sparks-fear-of-hotel-closures-and-food-price-hike-in-kerala/article70726244.ece
Processing: https://www.thehindu.com/news/national/tamil-nadu/israel-iran-war-lpg-crisis-coimbatore-hotels-cut-service-timings-menus/article70725515.ece
Processing: https://www.bhaskarenglish.in/local/rajasthan/news/rajasthan-commercial-lpg-supply-increase-hotels-restaurants-137498662.html
Processing: https://www.tribuneindia.com/news/india/lpg-shortage-cripples-hotels-restaurants-nationwide-bengaluru-mumbai-among-major-cities-hit/
Processing: https://www.thehindu.com/news/cities/Hyderabad/lpg-cylinder-shortage-forces-hyderabad-hotels-to-scale-down-menus-possible-closure-clouds-establishments/article70730036.ece
Processing: https://www.livemint.com/news/india/half-of-mumbai-hotels-restaurants-could-shut-shop-this-week-amid-acute-lpg-shortage-no-more-dining-out-what-we-know-11773115698078.html
Processing: https://timesofindia.indiatimes.com/city/mumbai/hotels-now-stare-at-shutdown-prospects-gas-to-last-till-thurs/articleshow/129474176.cms
Processing: https://www.moneycontrol.com/city/lpg-shortage-in-hyderabad-large-part-of-food-industry-could-temporarily-shut-down-article-13856571.html
Processing: https://www.bhaskarenglish.in/local/gujarat/ahmedabad/news/gujarat-commercial-cylinder-shortage-food-traders-lpg-supply-137404656.html
Processing: https://economictimes.indiatimes.com/industry/services/hotels-/-restaurants/lpg-crisis-gas-prices-hike-india-today-roti-dosa-pooris-disappear-from-menus-across-india-as-shortage-hits-eateries/articleshow/129495949.cms?from=mdr
Processing: https://www.thehindu.com/news/national/kerala/lpg-shortage-hits-hotels-in-keralas-kannur-about-40-units-face-closure-black-marketing-alleged/article70738413.ece
Processing: https://www.deccanherald.com/india/lpg-shortage-20-hotels-restaurants-shut-down-in-mumbai-operations-hit-in-bengaluru-chennai-3926080
Processing: https://www.republicworld.com/india/commercial-lpg-shortage-hits-mumbai-and-chennai-big-20-hotels-and-restaurants-shut
Processing: https://timesofindia.indiatimes.com/city/goa/restaurants-adapt-to-lpg-shortage-as-west-asia-war-turns-up-the-heat/articleshow/129579939.cms
Processing: https://timesofindia.indiatimes.com/city/chennai/gas-crisis-hits-over-10000-chennai-hotels-as-lpg-supply-dwindles-amid-west-asia-tensions-eateries-warn-of-shutdown/articleshow/129433888.cms
Processing: https://www.thehindu.com/news/national/karnataka/lpg-shortage-crisis-north-karnataka-hotels-and-eateries-facing-imminent-scarcity-of-gas-cylingers/article70726637.ece
Processing: https://www.bhaskarenglish.in/local/uttarakhand/news/dehradun-lpg-crisis-hotels-restaurants-limited-menu-137412807.html
Processing: https://www.storyboard18.com/trending/explained-what-is-driving-indias-lpg-shortage-and-how-hotels-and-restaurants-are-coping-ws-l-92229.htm
Processing: https://www.newindianexpress.com/cities/bhubaneswar/2026/Mar/11/lpg-crisis-odisha-hotels-restaurants-short-supplied
Processing: https://www.patrika.com/en/jaipur-news/rajasthan-lpg-crisis-eases-supply-to-50000-hotels-restaurants-resumes-today-20428033
Processing: https://www.tribuneindia.com/news/india/lpg-shortage-indians-stare-at-their-kitchens-as-iran-war-makes-cooking-gas-scarce/
Processing: https://www.bbc.com/news/articles/cm2xg0p4y84o
Processing: https://www.thehindu.com/business/Economy/oil-ministry-sets-up-panel-as-commercial-lpg-shortage-hits-hospitality-sector/article70725110.ece
Processing: https://timesofindia.indiatimes.com/city/chandigarh/gas-crisis-leaves-himachals-hospitality-industry-on-the-boil-majority-eateries-to-run-out-of-fuel-in-a-day-or-2/articleshow/129474956.cms
Processing: https://www.livelaw.in/high-court/karnataka-high-court/karnataka-high-court-commercial-lpg-shortage-affecting-hotels-526850
Processing: https://www.thehindu.com/news/national/karnataka/lpg-cylinder-shortage-nearly-90-of-hotels-in-shivamogga-to-close-down-operations-on-march-12/article70730453.ece
Processing: https://www.hindustantimes.com/india-news/bengaluru-chennai-restaurants-may-halt-ops-today-amid-lpg-shortage-panic-in-gurugram-and-mumbai-today-101773115085896.html
Failed: https://www.hindustantimes.com/india-news/bengaluru-chennai-restaurants-may-halt-ops-today-amid-lpg-shortage-panic-in-gurugram-and-mumbai-today-101773115085896.html
Processing: https://patnapress.com/lpg-shortage-hits-bihar-hotels-and-tea-stalls-prices-of-tea-samosa-and-thali-rise/
Processing: https://www.etvbharat.com/en/bharat/union-petroleum-ministry-boosts-commercial-lpg-supply-by-20-per-cent-to-support-restaurants-hotels-and-migrant-workers-enn26032104949
Processing: https://www.moneycontrol.com/news/trends/bengaluru-restaurant-adds-gas-crisis-charge-to-bill-amid-lpg-supply-crisis-internet-reacts-13861884.html
Processing: https://www.deccanherald.com/india/maharashtra/lpg-shortage-50-hotels-restaurants-in-mumbai-may-shut-operations-after-two-days-3926366
Processing: https://www.lokmattimes.com/maharashtra/maharashtra-lpg-cylinder-govt-announces-20-extra-supply-big-relief-for-hotels-and-restaurants-amid-global-fuel-crisis-a525/
Processing: https://www.hindustantimes.com/cities/chandigarh-news/lpgshortage-fear-grips-region-hotels-restaurants-worst-hit-101773169887592.html
Failed: https://www.hindustantimes.com/cities/chandigarh-news/lpgshortage-fear-grips-region-hotels-restaurants-worst-hit-101773169887592.html
Processing: https://indianexpress.com/article/cities/lucknow/hard-make-meals-guests-lpg-supply-hit-up-hotels-restaurants-cylinders-10575131/
Processing: https://sundayguardianlive.com/india/lpg-shortage-crisis-how-gas-supply-disruptions-are-impacting-mumbai-restaurants-and-hotels-175245/
Processing: https://indianexpress.com/article/cities/kolkata/west-bengal-restaurant-crisis-lpg-shortage-west-asia-strait-of-hormuz-10578517/
Processing: https://www.thehindu.com/business/Industry/indias-lng-lpg-shortage-to-be-short-lived-as-new-supply-routes-domestic-production-kick-in/article70726993.ece
Processing: https://openthemagazine.com/india/lpg-shortage-hits-restaurants-in-bhopal-and-hyderabad-as-businesses-turn-to-alternatives
Processing: https://thefederal.com/category/business/lpg-crisis-india-restaurants-closure-jobs-food-industry-233977
Processing: https://www.news18.com/cities/new-delhi-news/gas-stations-shut-in-bengaluru-75-drop-in-hyderabad-how-cities-are-coping-with-lpg-crisis-today-ws-l-9953948.html
Processing: https://bangaloremirror.indiatimes.com/bangalore/others/war-updates-lpg-shortage-disrupts-food-supply-chain-across-bengaluru/articleshow/129562302.cms
Processing: https://timesofindia.indiatimes.com/city/kochi/lpg-crisis-pushes-hospitality-sector-to-brink/articleshow/129412858.cms
Processing: https://www.indiatoday.in/india/story/lpg-cooking-gas-cylinder-shortage-domestic-hotel-middle-east-conflict-iran-war-oil-supply-2880287-2026-03-11
Processing: https://www.indiatvnews.com/maharashtra/20-of-mumbai-s-hotels-closed-due-to-lpg-shortage-if-crisis-continues-50-of-hotels-could-close-in-2-3-days-2026-03-10-1033221
Processing: https://timesofindia.indiatimes.com/business/india-business/iran-war-impact-on-india-lpg-shortage-concerns-rise-which-states-may-feel-the-heat/articleshow/129383455.cms
Processing: https://economictimes.indiatimes.com/news/new-updates/lpg-shortage-bengaluru-hotels-close-today-which-major-cities-will-suffer-worst-and-what-it-means-for-students-and-office-goers-relying-on-mess/articleshow/129376595.cms?from=mdr
Processing: https://www.cnbctv18.com/hospitality/what-behind-lpg-shortage-and-how-hotels-restaurants-are-coping-ws-el-19868209.htm
Processing: https://www.business-standard.com/markets/news/lpg-shortage-shuts-restaurants-across-cities-qsr-eternal-swiggy-stocks-fall-126031000704_1.html
Processing: https://www.deccanherald.com/india/karnataka/bengaluru/bengaluru-hotels-slash-menus-hunt-firewood-amid-lpg-shortage-3927277
Processing: https://www.thehindu.com/news/cities/Hyderabad/lpg-shortage-looms-large-but-hyderabad-haleem-to-stay-on-menu/article70725434.ece
Processing: https://www.deccanherald.com/india/lpg-crisis-restaurants-levy-gas-surcharge-on-customer-bills-amid-lpg-supply-crunch-3933317
Processing: https://www.bhaskarenglish.in/local/mp/bhopal/news/madhya-pradesh-gas-shortage-hotel-restaurant-shutdown-fear-137400206.html
Processing: https://www.thehindu.com/news/national/kerala/lpg-shortage-forces-closure-of-over-100-kochi-hotels/article70738549.ece
Processing: https://www.siasat.com/lpg-shortage-hits-hyderabad-restaurants-amid-warning-of-possible-shutdown-3432559/
Processing: https://www.hindustantimes.com/india-news/home-lpg-gets-priority-hotels-fear-closure-govt-says-upping-production-as-oil-supply-hit-by-west-asia-crisis-updates-101773144074839.html
Failed: https://www.hindustantimes.com/india-news/home-lpg-gets-priority-hotels-fear-closure-govt-says-upping-production-as-oil-supply-hit-by-west-asia-crisis-updates-101773144074839.html
Processing: https://www.linkedin.com/posts/cnbc-tv18_lpg-lpgshortage-iranwar-activity-7437495780971712512-w5v7
Processing: https://www.indiatvnews.com/delhi/lpg-shortage-affects-gas-agencies-in-delhi-owners-say-hotels-not-received-supplies-for-last-2-days-2026-03-10-1033246
Processing: https://www.bhaskarenglish.in/local/rajasthan/news/jaipur-lpg-shortage-chapati-price-hike-induction-cooktop-out-of-stock-137415947.html
Processing: https://www.thehindu.com/food/features/indian-restaurants-cut-rava-dosas-parottas-and-pizza-as-lpg-shortage-spreads/article70725444.ece
Processing: https://thefederal.com/category/news/lpg-crisis-234765
Processing: https://timesofindia.indiatimes.com/city/dehradun/ukhand-eateries-hotels-hosps-turn-to-alternatives-amid-commercial-lpg-shortage/articleshow/129579334.cms
Processing: https://www.punekarnews.in/pune-lpg-shortage-hits-hotel-industry-10-15-restaurants-shut-many-operating-with-limited-menu/
Processing: https://energy.economictimes.indiatimes.com/news/oil-and-gas/lpg-shortage-crisis-restaurants-facing-retrontments-amid-supply-issues/129622574
Processing: https://www.telegraphindia.com/business/lpg-crisis-worsens-from-delhi-to-bihar-goa-to-uttarakhand-hotels-restaurants-on-verge-of-panic/cid/2150837
Processing: https://thesouthfirst.com/tamilnadu/lpg-shortage-hits-tamil-nadu-hotels-struggle-auto-rickshaws-off-roads-as-commercial-cylinder-supply-stops/
Processing: https://news.google.com/rss/articles/CBMiigJBVV95cUxNbDJtY3JGV3JMWWdtSjRvM0NYMjdHNXRnbzJtV2ZxVGd5U3o3a0dUSkV1ZnNRWEZlZVh2X2tvSTlJa0dmcUwyMXRnNl8wLUxZZXRBcUxGWnNfUmhrSlFJVm9kTkhkNkw5SjJNRHF1MVh2dldvem43YzhQU2Vsek0wSWg4VWxIZXZmU2pFNWVHOVdxSEdaS2wzNDFhdm93ZXRqVmF2M3lUZWY2WmsyU0dIbnRubUFxdERRMGN3aWs3LVQwMG92MUlGUFJzczh0a296NzhZZ0EzU2lvSlJ4QkVwY1RFYmtJUUlSX2RscEZSaHpmbTN0Z3ZEYVhnbzY1YWhyR3ZqX1VxSjJWd9IBjwJBVV95cUxOR21vX3FPTDJoN1RqNkZlQ19peUN4Nkxxc2JxUEN0Y0U3Qk9GcmxwUUpfcHd3dzRpMFlKZGVfRjU3N2dBOXlJcXdXY3FUVUJaR09EaUE3cTgyTHBNRG5uRjNiV2JQMklxTGVTOHd6aWxidlp1SUdIN2FOUVp2VWY5cy1XNGU0QUF5SFlaU1VsUXpHdjhRQnB3MXFNVmhaSE1LM3FGemNjdzBTODduRlJyOHdZWjA1ZDNyYU1mVVFxZEJsRUo2V3l3dm9uaTNrVERpazNfbzlRbkpIakkwRTR2SXNQbUFEb2Z6enJTYmhWRER4ZGpHdldmVWF5Q3Q2b3hucHF0MDlOWmxzYU5CZUtj?oc=5&hl=en-IN&gl=IN&ceid=IN:en
Processing: https://news.google.com/rss/articles/CBMi0wFBVV95cUxNMWxoVmw0N3NENkFjR29hOWdUTmNUSWsxMUFCZmp4Vmhzc0w5eUtEU1plS25SRHBqVlZVVU5xN2FmTXMtUlB2dGxTa2x5d3dUTkpJX0dsQzkwS2sxR2hZTnZhbTdDTkNRNmRreVQySDV1akZVZGhZd1RNSm4xdEoxSFE5R25PZVRHbUJKRGhFa1oxRGUtOFZrZklPWHRSWHBKQlVCMWU0c21PNjFvOC1RQlM4VTVUWGI3RkNuZjA4dFhQaWVBMDVOLWtHVldLR1VNazBF0gHYAUFVX3lxTE5DLU5BanhLaW9CQVN2Zkg5OUNlczRJcGxqRFN3OWtBUkRiWXN3WDlvSzJEaHlheTBoblhDNXZHTkJFZXhmVV9KQlN2M2F4d0ZWa2NyX09kLTFQYXJVUFhmQ016VzV1dFd0TGdZbzl2WUpVY005NnJaeDJJMEJmdWNWUVgtTEdZSGFlTVVxQU1IdG41a05ZNkdpbHVoU09lRXMzdnZEdGZkYkdsdnhidThjYmRwUUFma1lmRnZhT19LMjZLcGczazVHeF9HUWRxWkRjUlBmRmJ3Tg?oc=5&hl=en-IN&gl=IN&ceid=IN:en
Processing: https://www.millenniumpost.in/bengal/lpg-crisis-supply-stoppedin-siliguri-hotels-restaurants-651447
Processing: https://www.hindustantimes.com/real-estate/lpg-crisis-in-india-hits-restaurants-could-it-pressure-retail-rents-and-trigger-tenant-landlord-renegotiations-101773374312408.html
Failed: https://www.hindustantimes.com/real-estate/lpg-crisis-in-india-hits-restaurants-could-it-pressure-retail-rents-and-trigger-tenant-landlord-renegotiations-101773374312408.html
Processing: https://www.thehindu.com/news/cities/bangalore/lpg-crisis-forces-bengaluru-hotels-to-try-kerosene-stove-induction-cooktop-eateries-to-cut-down-on-timings/article70731683.ece
Processing: https://www.newindianexpress.com/cities/thiruvananthapuram/2026/Mar/12/hotels-in-thiruvananthapuram-reel-under-lpg-shortage

In [88]:
articles = get_relevant_articles()

for i, art in enumerate(articles):
    print(f"\nArticle {i+1}")
    print("URL:", art["url"])
    print("Preview:", art["text"])

Processing: https://news.google.com/rss/articles/CBMi1wJBVV95cUxPRVNnYVhMdnl2ekIySzRYTDMzSEdQeDdvREFVQlVrdWxtSW1uTE5QNG9Vc3lFZl9vNV9iaEZEaEhZemR4Z3ZOVFoxcVNsaVotRHVWeEE3Y3o4eW9oUlNBQkkxOE8tQjI5UTNLWlRDaWVjZlI0NWU1Qy0tblpJVzFVYmQ1UmNZOVZrVEx2XzZ4b3h3Tm9uRXFmekYxemdkdnVFZlg1VTNzY3oyOVczUU1PYzYxeTF5dEhaNjBSOW0xQ3JGTjJZWUNRaGlaWnFWbWdaS1VfRzVZanExZjdRdXkwQWlXbjdaMDdPTGpuQUVmeUFJOU1mS3Q1X0JrVlNidjVGN2tpSUVyTURRYnlOYUZvaGp6LWpyQnktaG9lVTZJbHJJZnZ5SXVpR2VVRFM1SUUzWnMtNzJYeXl0V3ZOdmdzY1VFdEZYOEhQdkh4aXcyWVRsTk8ydl9R?oc=5
Processing: https://news.google.com/rss/articles/CBMijwJBVV95cUxOT2hSQVVZdV9lQXpvenhiREdjVjV4MUtKSjd4QkxOZzV1NmpWcmlpVXlfRkw2cDItVVBiWXlWMkd3amJKRjlPZGNKbV96MXh2Y1dVVEtreGdvMFJGQWF4VjhjaWhzaDRlMXhvV1NHbEJFZVNuNGZFZGc0bEhHS2x0YTF2SC1fb0hoYmh6N0lIU2ZwUDQySnlqUGtYZTViNGRUOG9xcjRKRkFwRmltSTNiV3ZndFB5V1hKR3Z6VmE5R1ZOM211ZVZQUnR1ZjNNcE1WUjNnZm1GNWkycWpGVmdBZEdOVUptWTczOW13QzdkcDdaVk05azQ4S3FIRzFjVVJfRXRvQVJ5ZnhqQUpBQjNB0gGWAkFVX3lxTE9lSzRzZWltZXM4cmdXZlBrNDRsMU9BNzBnTzlQTXJKeTdCZm9VeFN4by1Zb1BGTGZGUTA1c2RuckxTQ3VDR2VYTHJzRE9fTFF0MkN5Z3BOcDZhNGRsci1wREFlZjRSQTdLSnpPZ1J5aHdUcnUtTkEyeDJKR1lYU3F0bjhDT0ZZSmgxMnhwaVlDMHRvY1c4MGxXam5WcEFEaVRmYUE5QUtKLTF4bmRxRXNMQnE4NGxPOWU1elI4bmV5V05sTnplTEdEZnREZlg3b2hoQ29lM0hUa2NvYThjbmFROXJwYnFpRC0wSXpyQTdCbVloX1BjZDBDZlNMVllhNmE2bjdEWktvWXVIaFhHb1BDbklYcEJR?oc=5
Processing: https://news.google.com/rss/articles/CBMi1AFBVV95cUxNT3JrVmpGcXJ6X05pN01udkl5blBzMkl6NVFEeGlsZEh6dWxhMGRuNlVUanRHZUUzVWdZd3BwaWlLUW13VlBqUGQ5ZWlkUkMxMmZiM2RKOFNNZTF4bzcyd1h3YThieTE5UVBhSWxZc0h1MnNUenhyaVFxUVE3c3VSWkFIdjJuR0laZzBoY2R3dXdESEk3cXRfczZtRFM0dFRvbEp6dkRFTWxLbmJJNUNDdEtjMGpTRFRyNmFST3ZjU1pqU0xiMWdoY29FTEpTMmEyZ0daWQ?oc=5
Processing: https://news.google.com/rss/articles/CBMi0wFBVV95cUxPaTlJNDNzdnJzS0p0SmhfSHZyajRwaUpvRW1VbGZTY1hVa0NvSHBqclFoaVBveTZqVXFNVkZKN3NDQUZOenQzUnpURGR0TldvOTFFT1l1djlBLS1TeVNsZ1AzSmJCT1BpaTVPZEVpQUtmR2hLdHlJbEV0VGFXVTJIR0Zmcm93cE9MX3FhanJlN0FDZXZHTDMwZXMzRC1VeDcxaWc4WnpQMkNHZXk1SHAycWEyLU1CR0hnNWM1QVl1eDVkRHVNQ0ZBVzFKal9TVmJsem5V0gHYAUFVX3lxTE9ZZmFXb3ROcWdZS0UwNVpuMFBxLXYwUHlYSUJpRFpCamE4ZWY1bENDbmpFTDN2NUV3TGtzVFJWbnZ4YmJEcGd6VG4xYjhDckdFeW9aN2twN2V4aU5HQmRwRnpoVUFsbmJGd01mV1huT3hDN0Q1T08yMlkzNFFVenNKbzZaTlVwcjhicWFLU3JtOE4xSkEtNU9JQWFIQkJ0ZlpYTktfOGNGVEpXMjZnUUpZUHFBRzZ0UWQzckJOMTBvRGNDZmpPOVZYSWtRZVNsM2R1aXFHNDMtWQ?oc=5
Processing: https://news.google.com/rss/articles/CBMi0AFBVV95cUxQcnZyeUVGNWRwSTlGM3otRnlHVGtYRkZ2djdkclBXMXdJaTZGMGlEZ1M0alliYUhDSms1YzBjNGVoNnR0dU1WT0ZYWEZvR3lfcktLV21GdkZzek9zWGljU0ZaS1dOWHItS1pBYS1meTVzVHZBMFUxVS1lZFhMTHY2QkpBVTJrY3RsWUd6ZUJZaEV5R00wM0loSzJ1VzRrMUhqNi1Ra0U5NElTSkJJSnZJeE1VX0hGNWlGdE13TlR0NWpyWFFzNHlPaU9WMlRlN0lT?oc=5
Processing: https://news.google.com/rss/articles/CBMi7AFBVV95cUxQZTN0clg3QXc4RDloLW1zVFdaWUEyVVlCMTkwMndXMnY1VGVXdmZUYWhoU0JvWXpPcFpGbHFsTnpELVA1SWdtSDhTM3pGTWZ2QzZueDVzRmNBUWxWVmtVa0xCZ3pTQlhXb0VqUmFwN2RkNW9fS3hEaVVKOWY0TWJQOHJwV3lZaUYxQjB2c0NKd1htX3ktQ2FNWlpCTmloMUk3OHNQUGR4MFZ4WmpralBkajdYemYtemdBTEpRUmJ4dERuS3UxTnpnNVhyQ0FBWS1mcGpMeTd4RndjczJGcnZUSC0xTXZkQ2c1ZThuLdIB8gFBVV95cUxQMlhtT0hJbldLcEkyYVViQ2sya0h6ZlJXck01bEVsQmRTOVNWa2g1bVQtU043NzNrSVJkZEdNdXhLY05lTE1IZ2h6bDVaaTFHNEhaM2FmZ2N1WG53dk84aEx4WUR1algxdnpXb2hKYkJ3MUQ5SkFSSGpMNzFfaDAxY0hqdjRvak5jeEdFLUw5cW1Od25lNFBkRVlLLUJPZFhZLS1QQ3dMYi0yZkJPeXlMQWdONkpobWo1NU53alNCdFNIcnVNTmpuLWpyZEt1WGc4eU9sWUZfckkwRXFmbDRQX21tWGQ3d1NUUk1oLWdOTmpyQQ?oc=5
Processing: https://news.google.com/rss/articles/CBMi9AFBVV95cUxPbHFoUnI0RUROSjJVWXBiNXVHaWc5UlppaGV4VTBlT1c4bmNpWlRhdmVjVEVvdWItdDVPUEk4OTkyMTN1OU00cVpTYjVsbnN3SHZGenhzQTFXd19OdzgzN0FUeDRqclB2d2s1RWNlUjRjLWdhc29yaGlpSDJ4WmMtU3NidGVTZ0h1eTMxeGdMZmZRVTBpRFhfUGYzUjc0a2x1ZzYwdHRyWG9ORy1SblVXSDdhQ1FLNi1GRTkxbWNJUUR1Tm9wN1R6bnZLOWlxQzk5cXUzc2daTTZKT0Q4RElabUY2ZXk0NnNPXzF2UXNEWGk4Mnln0gH6AUFVX3lxTE1RWjlzYmtKREJOeDhaT1JfRmFaaUJnSjVSdDRfb2stcWticS10V1FfWHdQMlNZU1kyQ05yMkRReWY1c25KX0dYUGZQcXB5c3YtLXVqOXVPZWgzTmFRQUlJZVJyaWw3cEpQSzVNWGtpOUZ1a1BlS2NnNGZhZFBISjlyeEtsSDlveGwzNHY4dU9oVERaczFQX0VPTG1mNmI3Q05rNzFfd1djOWtVeF9iMXA2eFpVSFpGMGdxRVEyUjJZTlFQZzFCSWwwcHJYRHBPRlhTeVV5V3VqQWw5TXFqWXFoM0IzUWxVSWlwVE1nWEFMTWxNdXNHTFctU2c?oc=5
Processing: https://news.google.com/rss/articles/CBMikAJBVV95cUxOcWQtajVzQk1HNXpKWjBqaW1mT1NoYWh0SjkweC1uUnlYT3g1NnpHVzI0S2xrSGhvUXk2cGJBV3BpU3NJOU5EamdVRUpYa1JtMS1QWUFPbVJ3LXNuRTRCZGwyazBmbnBaTEx5eEV4N2VUVnNjRDZEcTl0TEhmQU5QdVBBM2Ewb2prQ0FOZXdQYXlKaWJJU2tzUFlZdEtOXzY1S2ZYQ21US3JCQ0lYY25HMTI2b05wMHFweWUyR1NYVEFXQ1hha3ozSUZWUC1vbFVCQlZ4enc2VzRKTHlmbU5qNm9hUnpiMnpfMF9LUk4wb2lKSDh1MzNYUV95aGk4aFpBb3BxUWRQVDliTkxkLWV3S9IBlwJBVV95cUxNSnN1Sjg3TTZjWGc1VXh1bC1oWVdidWxnMDVCd2lvMEE3eklFR2Q1cUhMM0RGcUw3MWYydDIwX29hc1FJdVlLZnI5UGowdVhEb0FVQkpGT19CWVlIT2VKV19CLWl3RUFXUlY2bHcyY3VJR3JKdjdRei1YbUNrNVE2dy1tTVZjZDd2VFFIWWxYRVJFZUZQVXo5S0pxSmVPRU9OSDRyYVVEV05ibTVRNnpVOHpjNmRpcWRmQzM1N212RmF2ZWlZNkxVZk1kVzVTOVh5NU1jcHprYnVEcXg4ZVl1VjQ1NThGXy1iMDFmNzZiaDNKMUVKN1VPTkRVd2NuNkF1ZTlGbmNpQkpyU3dIU2FCdnhDOURadDg?oc=5
Processing: https://news.google.com/rss/articles/CBMi_AFBVV95cUxQMW9yZjB0cWFRV1QyQjlONU13UzZueVhXel9UV1ppMjl4NnAwNVV2VHQtbjJnY0pWNi1ORkwwQjVuVEdSbXkwTTd2Wk51c0k4Y3NieWhVSlV2ZFpjbXZRM2tTdE45emlLSUUtalhuSzY0d3dFQzQ0OTc5aUtaak9raF9vRXBWSWlDMEZEUzRlLUtZby1SajRsaHNtUG9nMHNOOHZzWXdCcWltTDUzNDAzQngzUWtoYWxtd0YzbHRKeGZuSTZNTS1ZM0t0VlhtZjZBQjNjV2E0NW9rT002RkItQXFRUURqaGZiS0YwT00yVlB3T3RJZWRrdXlZem3SAYICQVVfeXFMTVFxS0s3MHR1cC1CTXd3el9qd1NLYm1nZHI2cTF0NTZYcGx4YVE5NXlraVVlSVRISFJ0Ny1WZmJRZDZpS1RqdEJHc1FLV2xrNGZ5MEQ5a1ozUF9lX21EUEhxTjA3eFNKZXJKODVTQ1drQUVsZ1RpdXVXaHJMX3Y1UW12WE1xcWNEamlXcktmSE1VY1pFbmtJaUtUNVgxVVNYUkROSVpTYjZNcGstNExRZjdBaXQtYW9XUHFuOFVieEwzTER2ZkVqTkZ5Ynh0TldTbTdOY0hsWGxOLUs2VHI0NFFBZUNMOEtKdzZFdXRzQU41TmRrTDlFU1FvSHVqb3ZIaFln?oc=5
Processing: https://news.google.com/rss/articles/CBMi_wFBVV95cUxOT2taT3pXcHBUMUhSWjBXODBmb0x3ZWlmSk81dndiY0tTeEJOQ1pCMjB4V3Z3S085NHgwdDRSX0xBRHRmeGN6V1R3bDNRRWNqQXREVnBGTUhXYWp6U09OMkxFNlFCRkRmR2lZeVVwV1I3LUZPendGNUUzeTVsOGM4bmkzTFRQc09qV1JHajRqN2VkZ1cxSDY1WFU3NWFpMTBWYUFLSjJOOEpXY1dtMGpFTEpYcjNweXRocWpKVUpTY3RSRkZhT3k5RjA4MjZ6VnhQdHhBZnZkUGhOMkd0clNTWm1ZbnA4cm92S2dBeXNndmZFZUh3VEY0dUtTMWVzdWM?oc=5
Processing: https://news.google.com/rss/articles/CBMi7wFBVV95cUxNQjVzWEFidk53NU9BX3JRUWpmX0JVaTd1STBWMWhieGRXd2NpdzB6R0V2VWVFV2hPWERFNDdsNThwa2lHQzFhTTJkNmF6TFFEaGtYb1dUaDZlQUdWNEhmNTlILV9ZbXZzS0thckNhU29vSGFaVnVaWkRqUWZVaWZZTENwRkVVTGkxdHNpNEJzNGd0RUJRdHMxWmdETG5SNEwyLUI5bHlYRU82eDE2c1JzWjh5bDVXTkZ3UFhRNlVCdUlBbGNlSnRpNmtoWE9DUkd2U2g2ajdvTjJPUVpad1NqeTFyY2c5eXJyVWVqaGNHNNIB9gFBVV95cUxPRGxBcXVfNFVEXzRfZUFTeWp6RkJtdmVkQUhKT1JRZGt6RmhIdXRKdkdqVmZsdnBkejBXTXB5d190ME12ZTNpZkFFVDFDcHVPejlYem1aU2ppODNXOXF4Zi1QSVpzSnF4cVJOaWl2MHJVT3ZqWGxBX3E2X19JbUhXQndBUVVtYVc2aFdUSnV4Y3A3eVpreUFkU05ibFY5RUVxQ1kyV1h6SkZFWG42bHdIQTNFM3FnRGN4dTdJb09zaWNwcHZFckpxOE9uUFJpUDZSRzRkVGFQWHlDTVNESmN5VlIwZUEyMl9SRkNIWVJERm1MZlQ0TFE?oc=5
Processing: https://news.google.com/rss/articles/CBMiyAFBVV95cUxOdWpUUXdhZWJPLXJVN2dEOGdSdDZ4aUVJUHdxbnBiTk9lWEZrSFlqcHVSa2h1QlFkd3I2NlJ4SmFxMVQzeDQzVFhhNlNwWjcyanVxUmtqMDJUWFQ5MFBuMF9WcXhSVV9PQVZ3a2FfYlhYRzROWXcxRVJfWW9ETHZXX05yRkdtVDVrNlVHb0tEVk5JVFFnRkY3bkEwWVBjdDc3SGVMZmxaSGtJU2VidEN5S05kT3E4UHcybW9JT2V6UFBpWTVvUlNibA?oc=5
Processing: https://news.google.com/rss/articles/CBMi1wFBVV95cUxNUTNSbERhdDRDODNVNzF2VVoxelVUeHp4LVFXOUpYbVktTUpzQzZQRmZjUjFwdXltUlowdEFya25Gekd3UWZJVTVHZU5YcHdUbU44NjZTdW1tXzV6ajU4MW8zYWttWGlTMmZpOThZZWNVV2Z3YkV0TnhiYzl1LUl0dHBWWU5zcVNrVm9zWEU1MzI5T2h5Q0hidkNHUUpjb2J2enRLUnNWNndVdWU0QTZSa1o1RmxETTBaLURRY05EamNXSHF4Ujc1SU8yVGFBNlRwNzRiUU9KSdIB3gFBVV95cUxNaXVkV0plYzZ6aUlxUm50SmlHcnJvVE1hWXBHR3ZBTWhFQmZGU2xwbUMtRDhGWDNMOGo3OHIxZEpUSFdiZUNZdjdOb2t6SE5ScXEtcFpfbXlJd2VRU0VxTXJ2SnlZWV9BQmZIMzZDT1hOdVE2VW5hYkF0TWNVNW83RTd1TmkzMlprMzRDbUUzREl6aDN3RlcySmVJbnJfNTc4czE2NDhOUFpXN1c0YTZVakI3djYzTkt4aEgwTFJiMmthQkt1MGZMMURYak0wQ0JsNGp2c1BYTHBzOUtoY1E?oc=5
Processing: https://news.google.com/rss/articles/CBMiwwFBVV95cUxPbVQ5X1V0TW1TdkxMaFJQSHJkQ0FYd3RHTXZBei1OUXRId1NhcmlNSzdHYkF5ZEVkcHlIQUkta0tFUkk3Z1hYcE1ZVmdocXZWazV6c1BtTjU4M3B4WEV5MHE2WDhGa0Vqa3FacVBKRUxtTEFKcUJDcFpKa0RWVXVWN1BuNk1uZXZGSDRqYUFWX2Rmci1INlB6VllUWTBpWHhXQ21ZX043RklPVlREWFdwLWR0QUV3cGt5VlNwamZHNGZWbVE?oc=5
Processing: https://news.google.com/rss/articles/CBMigwJBVV95cUxPVk8tOE00T0dqM3Fxc2JCSjVERVdlcWIwcmxZQzlLTVJJWXdjVWlzR0JBT1o2YXhJN1VoVTRldExGNnpRUWVMVjQwQm1xMzVROEw2LVFYVE9XY1pCTWliZHlyMXhsUmtvNkV2QW4xTGd5b29xeFFUdUNXWkRYUm9KT21KWVU0UTRmM1U0ZU5lUDJuRkdZYUFjcWZkaDE4c1JmMTM3RGNmZGpidTdwSWdnNkNDOEFvclJqMkh0T0piZGVrdjRya0VVeEEwWl9taW1jeUdNX2s1LVdQSkFkMTNKXzZWUVh3dDRBZUd1bTVRckJlNkhCUWhOakpvSDFYblB4d2Nv0gGKAkFVX3lxTE1aNWNiT21XeWVrR3QwZU9NakRaQjZGVVZkNGxrMFphNzBWRTJ5NHgzUUVMb3B2SThQSl9EMkJRYjFOVnFweFJLZ1VfTFVfLUJQQ0RyNmJrZEZkb2NwdlNMYlZrNUJKNk44SWxGUnNUNV9xNVZuQk9ueU96X25FbWJaR2VJUUNabnVLYzdyRUlmbzRyOFdQb3lmS0t0MFZkdVBGOHNPSWNrcVJfdnB5b1ZzdDJoaEJZb2RnYkkzZlQ2VXZJTEpvenFZekx3WTI5bHA1eFdsSnY0T1VTVnN5dlJmZTBxdk4tbUhLTGpqZERUSXZKckcxYnZybEZsaTZXaS1KT1NoZFYwN1ln?oc=5
Processing: https://news.google.com/rss/articles/CBMi1gFBVV95cUxQcHZVVm0yY21pT3lSTHNzSS1hMWNUWjBnYjg5TmI1MEs0X3lramFoMEZBRS1KbE1DR1pCcVd4MXNxWll3WjRBN1lQbzBNSlVvUXREcXJ4dGZBalZqNWpLd3JjdU9zbkpjT1ZzTmZFYnJHNVFDMFA4Q1E0c1VySmdWdW5YbEhEUDBQOExyRTBrUUlQMnd5eDhpOW8xaFJyenZ0ZU0wZjlJS3l2NFpaVS1sNmg4UEpDYXMxYUFvVnNUZ0RGdWItMFJKUjl0bUNXTzlKTmNlZUlB0gHcAUFVX3lxTE1FeWVxbVpkZ05id29jaHczSTdUOWxveUN3MlctVWZNSVM4Tk9yblNscjZXU2pIbWdBREdwYVFucUdmZFpRNGczWFd3QmswMzJkcFVQdXdwVHJ2M3pfZzY3NUFPOUF5WW5UNHB5R0Q4NVM2RklTQTBVM1V0YS1vY2VDZFJjTGlxNENVZXgwaHZ3MVE3elg4cjA3Vk1qYlI4emk2cC1VSnpSV3hMQnNBcVJoRjBGYWFKd0V1dTlmYUFCbnlsV0prSnhwLTZfb0ZIT0VHbXdveVRrd1VpSmc?oc=5
Processing: https://news.google.com/rss/articles/CBMitwFBVV95cUxOUnl5N19HdW1Ea21hWUJ2Rk5SaDhkY1gwdGhiU3liS3NjQXBOMnMycF9JX0xXVGlydTBIUk1hSWJ3bTc5ODhHMFpmN0RMWjM0YTZsZHV0SXhBZl9EQ3FiT3RET2ZmUWE2MnRzN0otdjdwS0E2bmlDNFJUMm44YUpxNksyeTZjWk1vR2pGV0p5LUJ2WXd1UXZKRUhKNTdYbnF5dlRNd0Z2ZlprYzd1c1hhZncwbEppTjjSAbcBQVVfeXFMTlJ5eTdfR3VtRGttYVlCdkZOUmg4ZGNYMHRoYlN5YktzY0FwTjJzMnBfSV9MV1RpcnUwSFJNYUlid203OTg4RzBaZjdETFozNGE2bGR1dEl4QWZfRENxYk90RE9mZlFhNjJ0czdKLXY3cEtBNm5pQzRSVDJuOGFKcTZLMnk2Y1pNb0dqRldKeS1Cdll3dVF2SkVISjU3WG5xeXZUTXdGdmZaa2M3dXNYYWZ3MGxKaU44?oc=5
Processing: https://news.google.com/rss/articles/CBMiigJBVV95cUxPRjkyMGNvQm1xZTFTT0hjd1hUR1RNelZYZXI0ZW1PTklOSmRxX3lpbU55NW1WaUxLZGxfbWREMWtkZUc4NDVObFYydDVwRlkzX05kY1gtdHpVYk1YVDFHRWh6TXVxMlRFX0h2N1cxNmVpeE1MLXgzZDVjSm1GVy16Zjl3Z0MzNnVZYVBkYXBMUDBPR0U3bTM3bkdNcl92US1veVdDVXVuVTJxLW5NTzZrd2FEZEVmcjFrR1JEYV9ZRFNNNE1Uc0xKOEkwd0pUTHF4M3NKeTMyWG5fTWJHTWlQZFJuUjBuTmtoMDVDQ0pMaWt2NWtVTmtQNEV3Tnhqc3pXVXhndmI1UjZjQdIBjwJBVV95cUxOMTZFYUtGUHlZd1RhTE9MNEw3VEpNRkdrSGxUb3NVdzFjeER6a0E1VnJoTFZscE42V2FGTV9ULXFVV1E1emEtZkF3bWc1YmFvc2ZDYWd2OEtHZ0ZST3J3NWlqUDF4QjluVmJzZVhyMWRmU2M5b3M0MGgzWWlLZVFrR1FWYnBvZl91REs2b3FGZDJiSnBndmVjRmx4MWNGLWV4UzBadGJPemh3c1JUeWZMZEV4QXFZZU9qVWRUZ19PMFVPRWRNZHpXb01zUmJMVVI1ZG4tc29jQzRfMi04MTRKZGkwMUdsZm5iUnMyRnIxX19BZjRLalhkRFJMX0VhYl9hVFBTZHJhMU1JaHQzNWlF?oc=5
Processing: https://news.google.com/rss/articles/CBMizAFBVV95cUxPOGprYjhERUtkM3dLNWF6cUltdUxNVk9wbHNoWFJQSFdQc2Y0ZG9Ed0RYTEdtM3FhR1YyLWZwVS1MWkIxTUk4Tno0d09mNnJpblNLUUVrY3BBcjlPdWwtQWZRTkJTTWhmWFlmUGRxblpqNm9OSFl6MU1oQ1dXMXNVNHZUdHlNRWUybGdCTWp6YmtIYkhhb1A3UUpXZ0pvR1Fia1FvenV6Z3E1M3daSXpyd0cxTEhBeTFPX3JCcnVVeWNYMGVCUFRtSDhITHQ?oc=5
Processing: https://news.google.com/rss/articles/CBMi-gFBVV95cUxQZVhMSVQ3U0Q4eTNUZUFONmxTanVmaFRFbzhwdUdRZXFsZVdNUWZCV3FJdzQxLVU3bFJOQW5WcDk4LWN4dzdvVGI1R1Y2TnFpN1VyQklWdlQ4Q09fRURMaF9WSHZyaU5IbnB0SWJ6SVNOSS1tTHN1N1RjV0FRWGJIWGMwanZoVmc3akdMcHM2MEFxVVlKZ0NrSXFsWUp6bE5qNVBNOXBvdFpTbUVha3kyTjFyUGgzVThLQUttU1JWcG40dFdVSE8yT1VBRHBfN3VkbUJvbDRkWkNoSURSVS1ieTlWNVpwSE1sMC0xU1duZlZFdXU3RXRhbGlB0gH_AUFVX3lxTE81MmJiUC1kTEtPcWZsYXR5cjJxNHp2QXVLei1LV3VId3NORHRLNmVMTDI4b0ZCRy16d0ZTaXRYNElIUEtCMVBhOUluU0RoYUlCR01MWkVqS2g0VnNUT2NhZmgwbUs1QzVhVXZ5dEQxb0tPc3JXMW5NaUJ4Mk4zcUQ0SWg2YWVsOHBPM3hSekNYXzRnOWFUbll6T2d4TDViTWVXQnd6ZGxzSzhTQVlaaHZ2UnJIT0FaM2RNMHh1aUVkVDRQbUo1VlRUSzRkazdGTnhFMWFWNEl6OEdsSXVkTVQ2b2xuQ1JmTTY1TmVLMEJaRm44Z3VQeVVOWlN6OEhXcw?oc=5
Processing: https://news.google.com/rss/articles/CBMicEFVX3lxTFBVcDBKeGlnYmdIRVpuU1NsaGxac0FFQzRNN25XX0tfRXJ2SElYdWV6MGVELWppMkJ2RFYyR0dKQmIzdUo0VmEyUW5fcXFHUl9Ua0tLQ2Z6cHJsM0dCeXpJV0JpVFViUDBiQmhzNGRteEo?oc=5
Processing: https://news.google.com/rss/articles/CBMitAFBVV95cUxQcTk1WXFHdVI1VWhtOFZ0cE5INThkamJaa0dTMTlVRzR0WERjSU1KWW0wdDNhZklic3J2V29qeVZzR0JFT1FNTXhIY3dvOUJySmNIZGdJNHhKVDFaTnFyejF3eVo1Ylpmb1hjTlU3anV5SVZ6bEwwRlRZUmM4ZkhSSXY4Y2FDUGVHZng1NURiMHg3Rk5CRWdadU1mMi1HSmFzQ19fU0paV1FOeW1YTXU0UU4xbmE?oc=5
Processing: https://news.google.com/rss/articles/CBMi0wFBVV95cUxOVHh1WlJMRXVBOUE3WjJDV1k0QnMzQl90STVjSjlXRVVoSUdPamlseGxJb1lhX3pwbnBfbzFyVDBncDJ1TC1jR1drOHlzQWw1RzYtRnN5aF8xdnR4NHR4X1dRRS1VTlR5WjkxSzBEcFktNDFsMTFUTmZvYXRUcS10em13b1Y3UW5sbXNPT2xURWdpbEVXMEVFWmVITzdkbkxYcjc3clg3T1dBdl9aUDJKdV8ydnNFVUxYalFLcXpUZHRId3JreDlKSTB5RFdscnJvdzk00gHaAUFVX3lxTE9KaTdreTFiVTZHajAtR2dhYW5NbTQ1cjRkYVJ4RTVkREFTSFFnYXJ1STVSRHgxRmJDcjgtMk5XQXJTd0xoN0w2cHhYOWdaS0tvcHNKMWJ4eVFnbEdybVk5M3JHcFNiYVpPc053RU1zUm9jTzRfLVhoZzRtU2NGcjJpemtBcGVZYW5uTHo5N042R1hmVE1FSTFpdXBTMU9aeDZDREgyaEpKbi1MVEdnTHNCLU41UWM2S25RajRfdFNxZTNScDZNbk9tUldLNzR1MV9XT0R2SVlOdFh3?oc=5
Processing: https://news.google.com/rss/articles/CBMi7wFBVV95cUxQU05wSElQSVFuY01obUlJSXQ2aURjcW5Kd3daMXpKTXNvbDVDb3RqSmE4ZEc2VEdhVzlfNFZuc1Q1cWhMQmNWYnhINFR0RXVsZ2xUbzM4M0tJQ2dLRHNfd0R4U0thNjBiRDItRUh5U0IyWGxodzk5dHZGcDdnT011SUJvdU1YREJYSjlWaTVzOWJBeUlQOHljV1FYbExGM2tzY0xRckpzRnRMZ3gzeDJvSjJtNlRlSGpFVENfc3VQUGhIb2VDNUhOZ1RqZkVjMFZVSUNZVEcyMjBDajYxSFRneUNQUU1MSkFaUW04d09tMNIB9gFBVV95cUxOY3F3TlFuSE0wVlZBYWNIbXlWc3BJSVhrYVNJNXY3aXlwVUIzM1Uwdlo0UDJZYnl1RzZMVUZZaXBWVVYtQnAzYlM3TzJJT09yTGVaM0VsUGtkYkQzVDR4TzJ1T2w1ZzM0Q2c4SjNzZVFYOTgzcEkzM3lVZFVfZmZ4OWdqWHB3RXBKY2JfdTBSMk1MSWxyRFM4Yzc0WjlKWmlkaEJhV01keTQ0UzVuVE9Oa1BEZEt5a0tLX2RBb3pEd3VLdkt3VDI2WkdEdXB3bFdTZlRzTUgwM0tubDBBVmFzYXRLR1FnZTdsUmk0VHVVOG1BVDlpNFE?oc=5
Processing: https://news.google.com/rss/articles/CBMiswFBVV95cUxQY0JJLV9ZRjlCTTk2YlQ2MUgweDhlQ0ZpdU1va21iNk1GUlZNeGtWSlhRTUdrVnhtMlZ6eEJmQ21mYk9LSm9DTTY3ek9PZEtyTVd3MlpOWi00Qm5tMWpkUVc2MEJrYldqM1V3RmNuNUtCa1JKdE93MDBfUEZTREhHUU1PcXFuUjE2bVpJSmpHN2VBLXRYUjRJVEdVRkZ6VEJmMG1GaWdVZVlEd3piRzZhRy1oOA?oc=5
Processing: https://news.google.com/rss/articles/CBMi4gFBVV95cUxNWm1rT0d5VDA2NTRGdUFJNk5UVnhxbkJ2TXNUODN4bFh3aTlwVWZhR2pMZDRFV1pkblUyeUpMLTV1czVlQVctTnBhbHVNWDJvUnZCcG40Um5mNTF3NVdDV1JNVmpUX09JbXhTM3UtTmRCQ0VmUnRFZmZfZldUUWM2MlhIVFM2WTdRQktsQWI0SnJlTlZiUkJoVVdJa0dfRkZ4eVZvSGlUaXRXU0hiSEl2QzNXeS12UTlwVkNFZ0VVQmxCQWFseTFQd2RqUUFrblZRWU54eHU5b2t4dU9jaWpXYkhB0gHnAUFVX3lxTFB0WmtqT0JEN3Y3ZzdLOE5aQXBzTTMxVnZhbGVkU3laSU5Od3ZQM3pnNGxlenV0SDdtYWF5WmdJdUFpTTNVd1VrWUZLaU9YZjNMYWhheXYxSHlHRVVNTThmanJrWUpsM0NmTHdGMjFwZjY5UDNQN29ZYXJSSUY2enFfTDNmOU9lMlJoNlNEVjI0LW15QXBBM2ZNY1RnYk5DVDN1djRqVGtCN1o3MmVRd0YzOXdwV0FkUkVpTnlQUUpsZ1lCWDI5MHVBRUpvZndfSXY1NFRlNEU5Q1prNjl2b2FBeDNIRW5zWQ?oc=5
Processing: https://news.google.com/rss/articles/CBMi7gFBVV95cUxNNWJhT1o0d0lkV3Z3enJFUnBVbkNtcWw5YXVnNTdQWFFzR0x2Q1RncDZhMHcwZzRVWHl2TWY2RWJtXzNOSDNyb1JLY2xVWEhUT1pNcnREUEJPanFKcnJEanZkeWJmYVNUOGh2elN1S2lVUmlvVGxnVEhpeGRvdnBtNDdOTjJzTmFtbDByWHItb3VPYmo3ODg5ZFpxX2dyVlZOWVZtRmVfMC1JdWpXb05CUUNzNHRVSjJDZ1U3N2x5MG5SSkJraVNnSWdNMGUycHhCX04wV3BKN3VYZkoyYWk1MzRiZkc0UWhMQ0xld0l30gH0AUFVX3lxTE1pMDhrUzF1OXhhSXNET3dMNWJFVlpNR3Y1blZEXzR2RGg2d2ZHT1h3M2h1REluV3NDQk4xQXBmWHF1YzdqY3daVi10QTdZenB6dWhkUTRKUjFNTmxVTV9aRm40Y0thY3JjYU8tMUFVbkZCNlVuWEJFamxSbU9wTnVCTllmenFqMEZqNV9QTmMtSndnUUFtZThZUEdVakhIOVdvMF9pR2kxM0t0UHFhS0VscDZRUThjdWxnWVRoY3Y5a3ZGYWwzb1l2LUtDTTdYZHFPeUdUN2VSUzRvZHNudHNWazVIdkQtZTJaOEUyd0ZCLW1hM0U?oc=5
Processing: https://news.google.com/rss/articles/CBMitgFBVV95cUxQdGJEZFNhTHFLaHR3bVprdjNGTGoyRXVYSW9peGFDdXBOTXVjRlJDYlV6R3N3ZU9QQ3MtdF8xc0o1MWd4TC1KQThXZ3FMNG05SkFlaTQ2NmZuM1BrdngxRUZqNVdnSFdRemFXby1BTTQ3UlFLckt5Z1UyTjhUYjZXWlZfa0VzTEljaHc3RUM3YVZIMHFRUWFnZmhObHlZT0dWNzdkbXBxc2RSd3BkMnRReFhYZllNd9IBwwFBVV95cUxPQ292N2pBeTVlUnpOV1ItOXRhemMxZWJwWWhRQ2JYdzhKZFFkNWRSclhkM2ptSUpFUWVYWXRMdElzaFE2TG1hUGtiV2p2TmRqZmRFdnNrTG94bldUOHRDbENua0lqSlZGaVZNLTc1dk5yMmJIZDh5TGg4TkJPX0x0QVF1OHA0Qy1XS0pmdXZTMGprQ04wYWd1TkE0Q3AyUWF4MnQ2UW1JbUF3TWVrcGcxLWNIMEhkTnNvOENzcGZjUFgzY0U?oc=5
Processing: https://news.google.com/rss/articles/CBMi_gFBVV95cUxOc0xhbHU3OWVvZUhqcXdzemNPN1Q1bGNyaFVkem9MZEpMWGZmSFd1cElYMlVaalBTaWNKZHZSQTBwR3p2ajZST09aVHdPOWdqS0tmcE5fa29DZGJDUTB6YzdUX1BJSnh1NnpuS09BQ1hTcmlManM3cVBkQURJQWctazhlS1lVX3pIYjBWNTU0TnB6T1pwbF9hNDQ0SC1QVzUyWmNFeV83NVFzR014aV9iV2Q3cmt2Um1uR2ZQUzdBOHF2bWZwNk1iTFJsbkQtQXRaenoyUjlzcTFreFVETnFqQXJCSVYxQlBZcmhxalUza3pJT1l3bEUxandxYWQ1d9IBgwJBVV95cUxOMHo3YmJYcGtPV1BZYWtpX2VhUEJ5QnBqMUpoZUpPVVRNVjVWaFZNNmxidXJUWHRnN2lhdmNKaGRUanlCWGQ3Vl9tSkJ0VVlzWjJ0Y0Qza3N6VThRT2d4cGtXczZoOThVaVl5bU5FRzVDSFpBaXphUGRPbzhScFJBcV9pd1JDaWZoSXZHODRFYmc1bE8zUWx6djlBbEtWUjYzZExwUkQ0OVZUc3FqVnB5d3RnaWQ2X2VJalJ1Qk5xTm5RTE1SaFZJUkU0WkRKSmdrbGE5ZUdRYXJhQU1BLVpkd1QzNFp1UVBNc3RMZ3ZmcV9DNkF1Z0JGTzNDSEdWb0hTbHNj?oc=5
Processing: https://news.google.com/rss/articles/CBMi1AFBVV95cUxNeS1Pb2NLTDd0bUxod1c5VHNCY0szVF9aNl9Oc2wyQkZsMFY0eEtCNDBtTWFRQnh2SGRYZHZXQ3pQTlROOUxCeUJsY3gxakNLUUc1V2hOSmNZeDFITVlWb05qWVNETnBYRUJPVUt4MjlwRmE4amFlT2xiTVFrMzBiNW1pX2dhTno3ZDR3dFBrdWxoT3owQ3Q2WXhnUUVneFZOdklzLUpsemJvb1REVG1vZ3k0M0dGbmk5UUFqRE91eTRlbG1aUXFtYUNzRC1nMnluWTNBOdIB2wFBVV95cUxOR0h1OTN1MXlUUkJDSnVrNlAzOTRtb3ZxLWtDUlJ3YjJ6UDAyLVhCdjRJX3ZrME1VRVhEZThxZHZNWTRRMDJBSl9ENHVMZmNiSzN6R3JHTmNfVmZZVjNIUWp2Q2JEU1pnbHRiYXp5cGxoMHVnaWczVV9qdVFIUEF6N29fUExvVnZpMXVkU1h4SmduQy1faXlhRkgzQWg1TkRxN1NJcV83T3JOVUNOTm1Sb1pRZTQtQm5SSm9faWxDOXc4cWdVXzNNZF9Ka0J4a0FHOEdUUTdyR2NPOFU?oc=5
Processing: https://news.google.com/rss/articles/CBMi1wFBVV95cUxNUUFFS3oxNm8yRGp0MnowUHJZUncyVG5uNFNNQXc0LWtUWnRlYUFLNkg2V1NZVFMxdGQ3clgwTEJiTWdnMHp6dTVYVFNzTFF0Wmg0R0YyNGx5d0l0NHQyQ0pvamN4TVY3akk0UnhvV2Z6NTV1V1d3dk4yX0pSdGZTbFRhdUgybzVsSkJoOEtLQ25mTDh3ZHU0NF9pQVZXbGRUSk1HRkJKY2lFWnVRcVR1c2t6Z016aHA0Z3BHMUVuaFdlWnl3WWpJdXplNGFFLUpvWVUyMjBFa9IB3gFBVV95cUxQZGpGaHJtS1lYRTdZcGFEcVZiQXg4ekxvV0ZoVVc1UG9DRUNYZENoWlVDdUdBRFRuaEdtT3FjQkRZVUF5MU1hak95TktXb1FFRVJDbkVOQ1dWZDg1dENvZjFUczhvdk1VdGFkOUxocWc2S1lUWmgyN1pseHRWWW5BQlZaWlV3ay0xanVyamN4blY5dDZHZmhNT2lGMkZLbnhHemt2akRuRGdhbkFhWHdDa3oxQnZVaUwzVUlLRmpZbkFZaU1fTjFqNUM4Tl9od2FQektyalVvUWVoMUVtaGc?oc=5
Processing: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQQ090TVdEdXF4RFRMMUc1MDJZc3IyeS1ZNy1CQWYtdDV3Mm0zUlFlQzlqa0FIeE15SXRHYTFLNW5SQ040ZVNBLUcwZVhSdERmQlZHT1JoaFFKaU5ybENlX2NmMkwwSUdJSWJXRXRNTlFLLXR2eVgwdUMwRkFqbXJzeHEtU2JtOWhuRTVxRTgyMDY4cHkxT3Fqa19Lb1V5YW43QUZRdjRtcTZnNjdoaWR0TFB4b0NFdENzOVdfWktEcVliR2fSAcgBQVVfeXFMTVU2WUctaS1tUTdndW5JYTRLb28xcmFGaFNEbnZnN0gydHVxVjhIMEJMazhnZUkxdkVOQ2R1eldSV3RZRTNxWm9BUzNaVnVtaVl0WHROVnJ3ME5oZTExZ1RwM2EyTExkd2JzcWJsTXB5T3FvS0hSVWhpaG9laXBWSlA1QzY0MWVaZ2xLSURjNDZNSEw4TmxISGFrZXFEY2h0TTYtUUpibm1WSWRDSHh2b09CQzBkSGFIVmw0SGNXMmVEeWVSTWNfR20?oc=5
Processing: https://news.google.com/rss/articles/CBMizAFBVV95cUxPdm5RNHBTQ01JQ2IwOUpiTkZESENZYmJDUFNlTmdnSUlqTGxOOXJCaDkwNDBmVFF4dF8yVFpXUXBrSXBvRy1uLUM0VVlreGdwZjBiZXRKT01Ia05RdHZtLXFNdFpuZmVJcTB3bEhwaUZ0aUdRdnBzUmxJQTlwTWl1elFMa25pcE44LUhOOHRYNXpMeG9hbkNoT0pHTGw3MTY4MEt6dVU4c05lQmh2RGQ1Qk1rN2xsSEFtNFlyV0FtVnhtY2NiSjBhTFZ4SGjSAdABQVVfeXFMUDNlTFZtb2h6N0Fra2hSTmZoS0YwRGZPQkV3c1psWG9MakotTFVwYU96dzQ1OFBWcEZVMVNldlZaVTVaTEFxRjZRXzd3aDdiR25mSVFBRVhhYzZTYkF6N3lmTWtyM3dfWERSQ2ZWa0x6eXpXb3dZejNKSkJHNGJraVViNDdLTkdQWTQ0Smw1QjkxRVNiZUNWeE40OHJEamRaX2JXQWxPOVJydTZZQUtZekNtNzRTMDUxdkFlaW54eFJzVUJYaXZ6dHRSQlRLcEtfdw?oc=5
Processing: https://news.google.com/rss/articles/CBMigAJBVV95cUxPdi1WTDJOSW9qaFlDV0NRZ0ZuaEtjTGEyTkNaYWpoV2V2SHBydzFWRXh0ckZBajl4RGFBaTE0eXQ2VGx5RFVIN3pvUTlwNU1zZjlJcWRDQnFWb0wxS2R2OUhKM2hlN2h5d2NlMVMtVlRhWDRXbTQ2WUxlNTEzZWkzQ3JDRlpXaUt0UFNCNmVTVVk2U2FhVGlEaTFSQ2JVdGJtRkVMR3hYNjFsU0lMSlZKcnV0QlItamFXc2lzdmJ6RjM1TVUxa25ZeXZiMHFqOUZMVmJIUUtEaHFuQURGRXFkRFRIbUY1My1ISEdNVWJhd0FsYnh3Q1NiaWNRRkt5eUEy0gGHAkFVX3lxTE5jZTVCOEYycENEM2Zxc3cyVkJtb1F0VENGd3o2bTZkeGotdzVLTWdkRm5uaHRCUDBkaVVIV1ZuS0xrejJmRS02RjdQNzJNSFFlRkkyWkNkMnVLNzhVV3ZNZXRLcHJmMXBaTGFtYlZVbXRyOWpZaDk0WXRZZVYwa29CdE5PWkFyVXlUaEkwdGktQkFMODdQMHU0d1FCZXdGYUkzSEUwS2pyOGRCcC13QkRwNmVMaEd5Z1FiSWU5N3pzRU5KN3BtaDltaVQxYXdlcWVmcXlEaXplTVo2OG1rLUg0WUdBdGZ0eU03LTdJVm1wTkFoeWRHU2JHcFY1bDBTbGJSNnpvUFI0?oc=5

In [35]:
for i, art in enumerate(articles):
    print(i,art['url'])

0 https://indianexpress.com/article/cities/bangalore/as-bengaluru-hotels-cut-menus-amid-lpg-crisis-how-this-restaurant-is-using-8-tonnes-of-city-waste-to-take-on-more-cooking-10598014/
1 https://www.bhaskarenglish.in/local/mp/news/mp-lpg-shortage-hotels-restaurants-hit-additional-chief-secretary-rashmi-shami-137506896.html
2 https://thenewsmill.com/2026/03/commercial-lpg-shortage-disrupts-hotels-as-government-prioritises-domestic-supply-amid-west-asia-conflict/
3 https://www.thegoan.net/goa-news/%EF%BB%BFlpg-shortage-pushes-south-goa-hotels-to-brink-owners-seek-cms-urgent-intervention/145485.html
4 https://economictimes.indiatimes.com/industry/energy/oil-gas/lpg-crisis-restaurant-body-seeks-relief-from-maha-government-amid-gas-shortage/articleshow/129647056.cms?from=mdr
5 https://www.indiatvnews.com/madhya-pradesh/mp-govt-allocates-9-lpg-to-hotels-restaurants-7-to-dhabas-in-big-relief-amid-commercial-lpg-shortage-2026-03-24-1034832
6 https://www.thehindu.com/news/national/karnataka/lpg-shortage-about-20-of-hotel-industry-needs-will-be-met-daily-with-immediate-effect-announces-karnataka-minister/article70775152.ece
7 https://www.thehindu.com/news/national/indian-hotels-grapple-with-gas-shortage-as-west-asia-conflict-prolongs/article70726061.ece
8 https://www.thehindu.com/news/national/maharashtra/commercial-lpg-quota-in-maharashtra-raised-by-20-on-centres-directive/article70772839.ece
9 https://www.thehindu.com/news/cities/Hyderabad/restaurateurs-in-hyderabad-face-concerns-over-commercial-lpg-supply-city-is-home-to-over-74000-restaurants/article70725637.ece
10 https://english.dainikjagranmpcg.com/states/madhya-pradesh/mp-commercial-lpg-supply-resumes-after-13-day-crisis/article-15879
11 https://www.thehindu.com/news/national/odisha/odisha-hotel-and-restaurant-association-flags-lpg-cylinder-shortage-issue/article70727224.ece
12 https://www.bhaskarenglish.in/amp/local/mp/news/mp-lpg-supply-hotels-restaurants-vendors-order-issued-137515516.html
13 https://hospitality.economictimes.indiatimes.com/news/operations/food-and-beverages/lpg-shortage-squeezes-food-industry-as-black-market-thrives-and-cylinder-prices-soar/129713438
14 https://timesofindia.indiatimes.com/city/mumbai/lpg-shortage-shuts-eateries-across-mumbai-up-to-20-hotels-restaurants-hit-says-industry-body/articleshow/129413549.cms
15 https://ommcomnews.com/odisha-news/food-supplies-minister-assures-adequate-lpg-stock-urges-calm-amid-gas-shortage/
16 https://www.thehindu.com/news/cities/mumbai/lpg-shortage-shuts-20-of-mumbai-eateries-industry-warns-of-wider-closures/article70726058.ece
17 https://www.thehindu.com/news/cities/bangalore/lpg-crisis-restaurants-in-bengaluru-likely-to-shut-services-as-lpg-supply-remains-uncertain/article70727551.ece
18 https://thefederal.com/category/business/lpg-shortage-hits-hotels-tamil-nadu-karnataka-bengaluru-menus-cut-233585
19 https://timesofindia.indiatimes.com/city/mumbai/lpg-shortage-20-commercial-piped-gas-cut-hits-hotels-food-chains-in-mumbai/articleshow/129587048.cms
20 https://www.thehindu.com/news/cities/Hyderabad/lpg-shortage-begins-to-hit-hyderabad-restaurants-as-menus-shrink-an-outlet-shut-for-friday/article70738442.ece
21 https://www.newindianexpress.com/states/kerala/2026/Mar/12/lpg-shortage-70-of-kerala-restaurants-to-shut-by-weekend
22 https://economictimes.indiatimes.com/industry/energy/oil-gas/shortage-of-commercial-lpg-could-hit-50-of-hotels-and-restuarants-in-mumbai-industry-bodies/articleshow/129385445.cms?from=mdr
23 https://www.thehindu.com/news/national/kerala/lgp-shortage-sparks-fear-of-hotel-closures-and-food-price-hike-in-kerala/article70726244.ece
24 https://www.thehindu.com/news/national/tamil-nadu/israel-iran-war-lpg-crisis-coimbatore-hotels-cut-service-timings-menus/article70725515.ece
25 https://www.bhaskarenglish.in/local/rajasthan/news/rajasthan-commercial-lpg-supply-increase-hotels-restaurants-137498662.html
26 https://www.tribuneindia.com/news/india/lpg-shortage-cripples-hotels-restaurants-nationwide-bengaluru-mumbai-among-major-cities-hit/
27 https://www.thehindu.com/news/cities/Hyderabad/lpg-cylinder-shortage-forces-hyderabad-hotels-to-scale-down-menus-possible-closure-clouds-establishments/article70730036.ece
28 https://www.livemint.com/news/india/half-of-mumbai-hotels-restaurants-could-shut-shop-this-week-amid-acute-lpg-shortage-no-more-dining-out-what-we-know-11773115698078.html
29 https://timesofindia.indiatimes.com/city/mumbai/hotels-now-stare-at-shutdown-prospects-gas-to-last-till-thurs/articleshow/129474176.cms
30 https://www.moneycontrol.com/city/lpg-shortage-in-hyderabad-large-part-of-food-industry-could-temporarily-shut-down-article-13856571.html
31 https://www.bhaskarenglish.in/local/gujarat/ahmedabad/news/gujarat-commercial-cylinder-shortage-food-traders-lpg-supply-137404656.html
32 https://economictimes.indiatimes.com/industry/services/hotels-/-restaurants/lpg-crisis-gas-prices-hike-india-today-roti-dosa-pooris-disappear-from-menus-across-india-as-shortage-hits-eateries/articleshow/129495949.cms?from=mdr
33 https://www.thehindu.com/news/national/kerala/lpg-shortage-hits-hotels-in-keralas-kannur-about-40-units-face-closure-black-marketing-alleged/article70738413.ece
34 https://www.deccanherald.com/india/lpg-shortage-20-hotels-restaurants-shut-down-in-mumbai-operations-hit-in-bengaluru-chennai-3926080
35 https://www.republicworld.com/india/commercial-lpg-shortage-hits-mumbai-and-chennai-big-20-hotels-and-restaurants-shut
36 https://timesofindia.indiatimes.com/city/goa/restaurants-adapt-to-lpg-shortage-as-west-asia-war-turns-up-the-heat/articleshow/129579939.cms
37 https://timesofindia.indiatimes.com/city/chennai/gas-crisis-hits-over-10000-chennai-hotels-as-lpg-supply-dwindles-amid-west-asia-tensions-eateries-warn-of-shutdown/articleshow/129433888.cms
38 https://www.thehindu.com/news/national/karnataka/lpg-shortage-crisis-north-karnataka-hotels-and-eateries-facing-imminent-scarcity-of-gas-cylingers/article70726637.ece
39 https://www.bhaskarenglish.in/local/uttarakhand/news/dehradun-lpg-crisis-hotels-restaurants-limited-menu-137412807.html
40 https://www.storyboard18.com/trending/explained-what-is-driving-indias-lpg-shortage-and-how-hotels-and-restaurants-are-coping-ws-l-92229.htm
41 https://www.newindianexpress.com/cities/bhubaneswar/2026/Mar/11/lpg-crisis-odisha-hotels-restaurants-short-supplied
42 https://www.patrika.com/en/jaipur-news/rajasthan-lpg-crisis-eases-supply-to-50000-hotels-restaurants-resumes-today-20428033
43 https://www.tribuneindia.com/news/india/lpg-shortage-indians-stare-at-their-kitchens-as-iran-war-makes-cooking-gas-scarce/
44 https://www.bbc.com/news/articles/cm2xg0p4y84o
45 https://www.thehindu.com/business/Economy/oil-ministry-sets-up-panel-as-commercial-lpg-shortage-hits-hospitality-sector/article70725110.ece
46 https://timesofindia.indiatimes.com/city/chandigarh/gas-crisis-leaves-himachals-hospitality-industry-on-the-boil-majority-eateries-to-run-out-of-fuel-in-a-day-or-2/articleshow/129474956.cms
47 https://www.livelaw.in/high-court/karnataka-high-court/karnataka-high-court-commercial-lpg-shortage-affecting-hotels-526850
48 https://www.thehindu.com/news/national/karnataka/lpg-cylinder-shortage-nearly-90-of-hotels-in-shivamogga-to-close-down-operations-on-march-12/article70730453.ece
49 https://patnapress.com/lpg-shortage-hits-bihar-hotels-and-tea-stalls-prices-of-tea-samosa-and-thali-rise/
50 https://www.etvbharat.com/en/bharat/union-petroleum-ministry-boosts-commercial-lpg-supply-by-20-per-cent-to-support-restaurants-hotels-and-migrant-workers-enn26032104949
51 https://www.moneycontrol.com/news/trends/bengaluru-restaurant-adds-gas-crisis-charge-to-bill-amid-lpg-supply-crisis-internet-reacts-13861884.html
52 https://www.deccanherald.com/india/maharashtra/lpg-shortage-50-hotels-restaurants-in-mumbai-may-shut-operations-after-two-days-3926366
53 https://www.lokmattimes.com/maharashtra/maharashtra-lpg-cylinder-govt-announces-20-extra-supply-big-relief-for-hotels-and-restaurants-amid-global-fuel-crisis-a525/
54 https://indianexpress.com/article/cities/lucknow/hard-make-meals-guests-lpg-supply-hit-up-hotels-restaurants-cylinders-10575131/
55 https://sundayguardianlive.com/india/lpg-shortage-crisis-how-gas-supply-disruptions-are-impacting-mumbai-restaurants-and-hotels-175245/
56 https://indianexpress.com/article/cities/kolkata/west-bengal-restaurant-crisis-lpg-shortage-west-asia-strait-of-hormuz-10578517/
57 https://openthemagazine.com/india/lpg-shortage-hits-restaurants-in-bhopal-and-hyderabad-as-businesses-turn-to-alternatives
58 https://thefederal.com/category/business/lpg-crisis-india-restaurants-closure-jobs-food-industry-233977
59 https://www.news18.com/cities/new-delhi-news/gas-stations-shut-in-bengaluru-75-drop-in-hyderabad-how-cities-are-coping-with-lpg-crisis-today-ws-l-9953948.html
60 https://bangaloremirror.indiatimes.com/bangalore/others/war-updates-lpg-shortage-disrupts-food-supply-chain-across-bengaluru/articleshow/129562302.cms
61 https://timesofindia.indiatimes.com/city/kochi/lpg-crisis-pushes-hospitality-sector-to-brink/articleshow/129412858.cms
62 https://www.indiatoday.in/india/story/lpg-cooking-gas-cylinder-shortage-domestic-hotel-middle-east-conflict-iran-war-oil-supply-2880287-2026-03-11
63 https://www.indiatvnews.com/maharashtra/20-of-mumbai-s-hotels-closed-due-to-lpg-shortage-if-crisis-continues-50-of-hotels-could-close-in-2-3-days-2026-03-10-1033221
64 https://timesofindia.indiatimes.com/business/india-business/iran-war-impact-on-india-lpg-shortage-concerns-rise-which-states-may-feel-the-heat/articleshow/129383455.cms
65 https://economictimes.indiatimes.com/news/new-updates/lpg-shortage-bengaluru-hotels-close-today-which-major-cities-will-suffer-worst-and-what-it-means-for-students-and-office-goers-relying-on-mess/articleshow/129376595.cms?from=mdr
66 https://www.cnbctv18.com/hospitality/what-behind-lpg-shortage-and-how-hotels-restaurants-are-coping-ws-el-19868209.htm
67 https://www.business-standard.com/markets/news/lpg-shortage-shuts-restaurants-across-cities-qsr-eternal-swiggy-stocks-fall-126031000704_1.html
68 https://www.deccanherald.com/india/karnataka/bengaluru/bengaluru-hotels-slash-menus-hunt-firewood-amid-lpg-shortage-3927277
69 https://www.thehindu.com/news/cities/Hyderabad/lpg-shortage-looms-large-but-hyderabad-haleem-to-stay-on-menu/article70725434.ece
70 https://www.bhaskarenglish.in/local/mp/bhopal/news/madhya-pradesh-gas-shortage-hotel-restaurant-shutdown-fear-137400206.html
71 https://www.thehindu.com/news/national/kerala/lpg-shortage-forces-closure-of-over-100-kochi-hotels/article70738549.ece
72 https://www.siasat.com/lpg-shortage-hits-hyderabad-restaurants-amid-warning-of-possible-shutdown-3432559/
73 https://www.linkedin.com/posts/cnbc-tv18_lpg-lpgshortage-iranwar-activity-7437495780971712512-w5v7
74 https://www.indiatvnews.com/delhi/lpg-shortage-affects-gas-agencies-in-delhi-owners-say-hotels-not-received-supplies-for-last-2-days-2026-03-10-1033246
75 https://www.bhaskarenglish.in/local/rajasthan/news/jaipur-lpg-shortage-chapati-price-hike-induction-cooktop-out-of-stock-137415947.html
76 https://www.thehindu.com/food/features/indian-restaurants-cut-rava-dosas-parottas-and-pizza-as-lpg-shortage-spreads/article70725444.ece
77 https://thefederal.com/category/news/lpg-crisis-234765
78 https://timesofindia.indiatimes.com/city/dehradun/ukhand-eateries-hotels-hosps-turn-to-alternatives-amid-commercial-lpg-shortage/articleshow/129579334.cms
79 https://www.punekarnews.in/pune-lpg-shortage-hits-hotel-industry-10-15-restaurants-shut-many-operating-with-limited-menu/
80 https://www.telegraphindia.com/business/lpg-crisis-worsens-from-delhi-to-bihar-goa-to-uttarakhand-hotels-restaurants-on-verge-of-panic/cid/2150837
81 https://thesouthfirst.com/tamilnadu/lpg-shortage-hits-tamil-nadu-hotels-struggle-auto-rickshaws-off-roads-as-commercial-cylinder-supply-stops/
82 https://www.millenniumpost.in/bengal/lpg-crisis-supply-stoppedin-siliguri-hotels-restaurants-651447
83 https://www.thehindu.com/news/cities/bangalore/lpg-crisis-forces-bengaluru-hotels-to-try-kerosene-stove-induction-cooktop-eateries-to-cut-down-on-timings/article70731683.ece
84 https://www.newindianexpress.com/cities/thiruvananthapuram/2026/Mar/12/hotels-in-thiruvananthapuram-reel-under-lpg-shortage

In [39]:
type(articles)
articles

[{'url': 'https://indianexpress.com/article/cities/bangalore/as-bengaluru-hotels-cut-menus-amid-lpg-crisis-how-this-restaurant-is-using-8-tonnes-of-city-waste-to-take-on-more-cooking-10598014/',
  'text': 'Even as many restaurants in Bengaluru cut their menus and scramble for alternative fuel amid a shortage of commercial LPG linked to the conflict in West Asia, one chain is expanding its cooking operations and supplying food to its 59 outlets across the city.\n\nAt the iconic Empire Hotel’s Koramangala branch, operations remain unaffected. In 2023, the restaurant switched to biomethane as its main cooking fuel through a tie-up with a civic waste management unit located next door.\n\nA biomethane plant at the Kasa Rasa waste management unit, built to process eight tonnes of wet waste into biogas, supplies about 120 kg of biomethane daily to the Empire Hotel on one of South Bengaluru’s busiest “eat streets.”\n\nAlso read | From coal and electricity to truncated menus: how Bengaluru eateries are dealing with LPG crisis\n\n“We are facing an LPG problem across our outlets and only the Koramangala unit is self-sustained because of the biomethane supply contract with the BBMP waste disposal plant located next door. Our entire cooking is with biogas,” said Abdul Gaffar, a cluster manager for the NKP Empire Hotel Group.\n\n“We are using the biogas to even cook our biryani for other outlets at present. We are using the Koramangala unit to cook food for the other outlets since there is a guaranteed supply of cooking fuel,” Gaffar said.\n\nHow the Koramangala biomethane plant works\n\nThe biomethane plant at the Koramangala waste disposal unit, set up by the erstwhile Bruhat Bengaluru Mahanagara Palike in collaboration with bioenergy start-up Carbon Masters, the Koramangala Residents Association, and the NGO Sahaas, was funded through CSR support from tech firm CGI, which invested Rs 2.4 crore in the project.\n\nThe plant processes eight tonnes of segregated wet waste every day, producing about 120 kg of odourless biomethane. This gas is supplied to the Empire Hotel next door via a pipeline.\n\nStory continues below this ad\n\nAn additional five-tonne-per-day waste-processing unit was inaugurated on March 21, as demand among Bengaluru restaurants for alternatives to LPG, including biomethane cylinders, grows.\n\n“For five tonnes of input processes, the capital will be about Rs 2.6 crore. This was the cost that was tendered (when the Koramangala plant was set up five years ago). As you scale, the cost will come down. If you set up a 100-tonne plant as per the Ministry of Housing and Urban Affairs estimate, the cost is Rs 32 crore,” said Som Narayan, the co-founder of Carbon Masters.\n\nCarbon Masters also operates a 50-tonne-per-day waste processing unit on the outskirts of Bengaluru. This facility is set to be scaled up to 200 tonnes and is expected to produce nearly 10,000 kg of biogas for supply. For the first time in South India, the gas will be distributed through a completed GAIL pipeline.\n\nAlso read | Delhi to Bengaluru, eateries feel the heat as black marketing of LPG cylinders surges\n\nCarbon Masters is also setting up a 1,000-tonne-per-day waste-to-energy plant at one of Bengaluru’s largest waste disposal units in Kasavanahalli, on the city’s outskirts. The project is being developed in collaboration with civic authorities and Saatarem Alternate Fuel Energy Pvt Ltd.\n\nStory continues below this ad\n\n“If all stakeholders get together, then the problem India faces of disposing 62 million tonnes of waste that is being produced can be solved, where it can be processed into useful climate-friendly products showcasing a circular economy model,” Narayan said.\n\nAccording to Narayan, biomethane can reduce costs by up to 15 per cent compared to LPG, especially when supplied through pipelines. It also offers environmental benefits by reducing reliance on fossil fuels and helping divert municipal waste.\n\nHowever, the fully operational biomethane plant at the Koramangala waste disposal unit, which supplies gas to the Empire Hotel, is relatively small compared to larger waste-to-energy projects yet to become operational across Bengaluru.\n\nFrom pilot project to growing demand\n\n“At present, we generate 300 cubic metres of raw gas and after purification, around 170 to 180 cubic metres of pure methane (around 120 kg) is obtained and supplied to the Empire Hotel,” said Manjunath, the Carbon Masters plant manager at Koramangala.\n\nStory continues below this ad\n\n“BBMP gives us eight tonnes of segregated wet waste. We shred the waste into small pieces and send it for anaerobic digestion. During anaerobic digestion, gas is produced. Methane is produced along with unwanted gases,” he said.\n\nHe said the gas is first sent to a storage balloon, where it is held before being purified to remove unwanted components such as hydrogen sulphide and carbon dioxide, leaving only methane. The methane is then stored, compressed, and supplied to the Empire Hotel under a commercial contract for cooking, he added.\n\n“We did the initial pilot where we were able to show them that organic waste, instead of being sent to landfills, can be converted into bio-CNG, which can be used for cooking by nearby restaurants,” said Narayan about the early days of biomethane production.\n\n“If the CSR funding takes care of the capital that is needed for starting the project, then the bio CNG production at the plant can take care of the operational costs and can be competitive versus LPG,” he added.\n\nStory continues below this ad\n\nAmid the conflict in West Asia and the resulting shortage of commercial LPG, Carbon Masters, co-founded by Som Narayan and a US-based partner, has been flooded with requests from restaurants for biogas supply.\n\n“There are normal restaurants that you would never have imagined would use green energy that are moving from fossil fuel to carbon-lite fuels,” Narayan said. “If you see some of our smaller restaurant customers, there are people using one cylinder or two cylinders per day, but there is so much demand right now.”\n\nScaling demand and business viability\n\nCompared to just three years ago, when Carbon Masters struggled to scale production, the current surge in demand is now driving the expansion of waste-to-energy enterprises, Narayan said.\n\n“It has been a challenge to scale in terms of making the gas available. Right now, restaurants are continuously calling. Back then, it was very hard. We got the initial buyers after a lot of effort. Now, India has passed a blending mandate. GAIL has become our customer, so we have a situation where the distributing company is itself buying gas from us,” Narayan said.\n\nStory continues below this ad\n\n“The cost of setting up a plant depends on the scale. For a larger plant processing 150 to 200 tonnes of waste per day, if the municipal authority provides the land and ensures feedstock delivery with a processing fee of around Rs 1,000–1,500 per tonne, I think private investors will come in and the government will not have to pay even the capital,” the Carbon Masters co-founder said.\n\n“If you do two small plants like five tonnes and 10 tonnes, it is not viable to recover the capital. In the case of small plants, the capital has to be paid through some kind of CSR or financing from the government,” he said.\n\nNarayan said there are three key components involved. The first is pre-processing the feedstock, since cleaner input material reduces the cost of extracting biogas. The second major cost is the anaerobic digesters, which are essentially RCC reactors. The third is the refinery unit, which separates and purifies the gas.\n\n“Bio methane is on par with LPG prices, and in use, it can provide a lot of savings, like, for instance, if the customer is not using it on a cylinder basis, then the pricing is for the amount of gas that is used. There is no wastage like in LPG cylinders. I would say there is about 15 per cent saving with bio methane when you compare it to LPG,” Narayan indicated.\n\nStory continues below this ad\n\nAround 12,000 kg of bio-CNG produced annually at the Koramangala plant for supply to Hotel Empire under a commercial contract in 2023 was estimated by some experts to be equivalent to about 600 LPG cylinders, or roughly 11,000 kg of commercial LPG.\n\nGovernment push and expansion vision\n\nKarnataka Transport Minister Ramalinga Reddy, whose constituency includes the Koramangala waste disposal unit, inaugurated a five-tonne-per-day waste-to-energy processing unit at the plant on March 21.\n\n“Initially, the processing capacity was eight tonnes of garbage per day. Today, we have inaugurated an additional five tonnes, taking the total capacity to 13 tonnes of wet waste being processed daily to produce gas,” Reddy said.\n\n“In Bengaluru, at least 2,500 to 3,000 tonnes of wet waste is generated every day. Most of it is dumped in yards along with dry waste, leading to problems such as foul smells, mosquito breeding, and contamination of water sources. If we properly utilise wet waste like this, about half of the city’s waste can be managed efficiently,” he said.\n\nStory continues below this ad\n\n“If we replicate this model in two or three locations in every Assembly constituency in Bengaluru, the city will not face a waste problem at all,” Reddy said.'},
 {'url': 'https://www.bhaskarenglish.in/local/mp/news/mp-lpg-shortage-hotels-restaurants-hit-additional-chief-secretary-rashmi-shami-137506896.html',
  'text': "English News\n\nLocal\n\nMp\n\nMP LPG Shortage Hits Hotels, Restaurants | ACS Rashmi Shami Meets Operators\n\nMP faces LPG shortage, hotels, restaurants hit for 12 days: Operators present concerns to Additional Chief Secretary; decision expected tomorrow\n\nBhopal 3 days ago\n\n\n\nCopy link\n\nHotel and Restaurant Association met Principal Secretary Rashmi Sharma on Sunday and raised demand for cylinder supply.\n\nThe LPG crisis continues in Madhya Pradesh. Hotels and restaurants have not received commercial cylinder supply for 12 consecutive days.\n\nRegarding this, on Sunday, the National Restaurant Association of India Madhya Pradesh Chapter and Federation of Hotel and Restaurant Association of India met with Additional Chief Secretary of Food and Civil Supplies Department, Rashmi Shami.\n\nChief Secretary Shami spoke with operators on the holiday and also held a meeting with oil companies.\n\nIt should be noted that while the oil companies' new guidelines mention providing 10% commercial cylinders, supply orders have not been issued. Due to this, more than 50 thousand hotels and restaurants in the state are under crisis. They are on the verge of closing down.\n\nBhopal Hotel and Restaurant Association President Tejkulpal Singh Pali said that the hotel business is on the verge of shutdown due to strict restrictions on commercial gas supply. Solutions were discussed regarding this. Demands were made to restore an uninterrupted gas supply, and a memorandum was submitted.\n\nNRAI representative Abhishek Baheti said that difficulties have increased due to the non-availability of commercial gas. In the absence of gas, hotel and restaurant operators are facing a major crisis. Demands have been made to resolve this issue.\n\nThere are more than 2000 hotels and restaurants in Bhopal. Demand has been made to provide cylinders soon.\n\nProblems in 2000 hotels in Bhopal Association President Pali said that hotels, restaurants, dhabas, food services, etc., in Bhopal play an important role in job creation and the local economy, but they are facing major operational difficulties due to a lack of commercial LPG cylinders.\n\nThey have demanded that a limited quota of commercial LPG cylinders be allocated to registered hotels and restaurants in Bhopal based on their actual operational requirements.\n\nEach establishment should be supplied with commercial LPG cylinders to maintain necessary kitchen operations and avoid disruption in food services. There are 2,000 hotels and restaurants in Bhopal where the situation has become serious.\n\nCentral Government's orders are not being implemented Madhya Pradesh Hotel and Restaurant Association President Sumit Suri said that representatives of hotel organizations across the state claim that despite the Center's supply order, no clear guidelines have been issued by the state government yet. Due to this, the local distribution system has come to a standstill.\n\nSuri said that we have placed our demands before the government and we hope that help will reach us as soon as possible. Millions of people's employment is connected to the Hotel and Restaurant Association. Everyone is facing a crisis of livelihood.\n\nSame rules for all hotels not right According to President Suri, the organization's main demand is to increase the current 20 percent limit to 50 percent so that businesses can operate smoothly. Additionally, they have put forward a new proposal that there should not be uniform supply rules for all establishments.\n\nThe gas quota should be determined based on the category of hotels and their demand. Larger establishments should be provided more gas according to their consumption, and smaller establishments should be provided with gas in proportion to their needs. Along with this, there is also a demand to increase the PNG supply according to requirements.\n\nThese officials were present NRAI representative Baheti said that the Principal Secretary has assured to provide gas to hotels and restaurants. He has also promised to take an appropriate decision by Monday.\n\nThe delegation included Sachin Agarwal, Deepesh Motwani, Shrikant Singh, Amit Baheti, Garvit Agarwal, Sagar Gaire, Vishnu Sharma, Kush Manohar, Sapan Arora, Dinesh Dawar, Jastej Pali, and others were also present."},
 {'url': 'https://thenewsmill.com/2026/03/commercial-lpg-shortage-disrupts-hotels-as-government-prioritises-domestic-supply-amid-west-asia-conflict/',

In [36]:
for i, art in enumerate(articles):

    file_content = art['text']
    file_path = fr"C:\Users\amolr\OneDrive\Desktop\News_Article\output{i}.txt"
    with open(file_path, "w") as text_file:
        text_file.write(file_content)

In [48]:
import pandas as pd
import numpy as np

In [71]:
articles

[{'url': 'https://indianexpress.com/article/cities/bangalore/as-bengaluru-hotels-cut-menus-amid-lpg-crisis-how-this-restaurant-is-using-8-tonnes-of-city-waste-to-take-on-more-cooking-10598014/',
  'text': 'Even as many restaurants in Bengaluru cut their menus and scramble for alternative fuel amid a shortage of commercial LPG linked to the conflict in West Asia, one chain is expanding its cooking operations and supplying food to its 59 outlets across the city.\n\nAt the iconic Empire Hotel’s Koramangala branch, operations remain unaffected. In 2023, the restaurant switched to biomethane as its main cooking fuel through a tie-up with a civic waste management unit located next door.\n\nA biomethane plant at the Kasa Rasa waste management unit, built to process eight tonnes of wet waste into biogas, supplies about 120 kg of biomethane daily to the Empire Hotel on one of South Bengaluru’s busiest “eat streets.”\n\nAlso read | From coal and electricity to truncated menus: how Bengaluru eateries are dealing with LPG crisis\n\n“We are facing an LPG problem across our outlets and only the Koramangala unit is self-sustained because of the biomethane supply contract with the BBMP waste disposal plant located next door. Our entire cooking is with biogas,” said Abdul Gaffar, a cluster manager for the NKP Empire Hotel Group.\n\n“We are using the biogas to even cook our biryani for other outlets at present. We are using the Koramangala unit to cook food for the other outlets since there is a guaranteed supply of cooking fuel,” Gaffar said.\n\nHow the Koramangala biomethane plant works\n\nThe biomethane plant at the Koramangala waste disposal unit, set up by the erstwhile Bruhat Bengaluru Mahanagara Palike in collaboration with bioenergy start-up Carbon Masters, the Koramangala Residents Association, and the NGO Sahaas, was funded through CSR support from tech firm CGI, which invested Rs 2.4 crore in the project.\n\nThe plant processes eight tonnes of segregated wet waste every day, producing about 120 kg of odourless biomethane. This gas is supplied to the Empire Hotel next door via a pipeline.\n\nStory continues below this ad\n\nAn additional five-tonne-per-day waste-processing unit was inaugurated on March 21, as demand among Bengaluru restaurants for alternatives to LPG, including biomethane cylinders, grows.\n\n“For five tonnes of input processes, the capital will be about Rs 2.6 crore. This was the cost that was tendered (when the Koramangala plant was set up five years ago). As you scale, the cost will come down. If you set up a 100-tonne plant as per the Ministry of Housing and Urban Affairs estimate, the cost is Rs 32 crore,” said Som Narayan, the co-founder of Carbon Masters.\n\nCarbon Masters also operates a 50-tonne-per-day waste processing unit on the outskirts of Bengaluru. This facility is set to be scaled up to 200 tonnes and is expected to produce nearly 10,000 kg of biogas for supply. For the first time in South India, the gas will be distributed through a completed GAIL pipeline.\n\nAlso read | Delhi to Bengaluru, eateries feel the heat as black marketing of LPG cylinders surges\n\nCarbon Masters is also setting up a 1,000-tonne-per-day waste-to-energy plant at one of Bengaluru’s largest waste disposal units in Kasavanahalli, on the city’s outskirts. The project is being developed in collaboration with civic authorities and Saatarem Alternate Fuel Energy Pvt Ltd.\n\nStory continues below this ad\n\n“If all stakeholders get together, then the problem India faces of disposing 62 million tonnes of waste that is being produced can be solved, where it can be processed into useful climate-friendly products showcasing a circular economy model,” Narayan said.\n\nAccording to Narayan, biomethane can reduce costs by up to 15 per cent compared to LPG, especially when supplied through pipelines. It also offers environmental benefits by reducing reliance on fossil fuels and helping divert municipal waste.\n\nHowever, the fully operational biomethane plant at the Koramangala waste disposal unit, which supplies gas to the Empire Hotel, is relatively small compared to larger waste-to-energy projects yet to become operational across Bengaluru.\n\nFrom pilot project to growing demand\n\n“At present, we generate 300 cubic metres of raw gas and after purification, around 170 to 180 cubic metres of pure methane (around 120 kg) is obtained and supplied to the Empire Hotel,” said Manjunath, the Carbon Masters plant manager at Koramangala.\n\nStory continues below this ad\n\n“BBMP gives us eight tonnes of segregated wet waste. We shred the waste into small pieces and send it for anaerobic digestion. During anaerobic digestion, gas is produced. Methane is produced along with unwanted gases,” he said.\n\nHe said the gas is first sent to a storage balloon, where it is held before being purified to remove unwanted components such as hydrogen sulphide and carbon dioxide, leaving only methane. The methane is then stored, compressed, and supplied to the Empire Hotel under a commercial contract for cooking, he added.\n\n“We did the initial pilot where we were able to show them that organic waste, instead of being sent to landfills, can be converted into bio-CNG, which can be used for cooking by nearby restaurants,” said Narayan about the early days of biomethane production.\n\n“If the CSR funding takes care of the capital that is needed for starting the project, then the bio CNG production at the plant can take care of the operational costs and can be competitive versus LPG,” he added.\n\nStory continues below this ad\n\nAmid the conflict in West Asia and the resulting shortage of commercial LPG, Carbon Masters, co-founded by Som Narayan and a US-based partner, has been flooded with requests from restaurants for biogas supply.\n\n“There are normal restaurants that you would never have imagined would use green energy that are moving from fossil fuel to carbon-lite fuels,” Narayan said. “If you see some of our smaller restaurant customers, there are people using one cylinder or two cylinders per day, but there is so much demand right now.”\n\nScaling demand and business viability\n\nCompared to just three years ago, when Carbon Masters struggled to scale production, the current surge in demand is now driving the expansion of waste-to-energy enterprises, Narayan said.\n\n“It has been a challenge to scale in terms of making the gas available. Right now, restaurants are continuously calling. Back then, it was very hard. We got the initial buyers after a lot of effort. Now, India has passed a blending mandate. GAIL has become our customer, so we have a situation where the distributing company is itself buying gas from us,” Narayan said.\n\nStory continues below this ad\n\n“The cost of setting up a plant depends on the scale. For a larger plant processing 150 to 200 tonnes of waste per day, if the municipal authority provides the land and ensures feedstock delivery with a processing fee of around Rs 1,000–1,500 per tonne, I think private investors will come in and the government will not have to pay even the capital,” the Carbon Masters co-founder said.\n\n“If you do two small plants like five tonnes and 10 tonnes, it is not viable to recover the capital. In the case of small plants, the capital has to be paid through some kind of CSR or financing from the government,” he said.\n\nNarayan said there are three key components involved. The first is pre-processing the feedstock, since cleaner input material reduces the cost of extracting biogas. The second major cost is the anaerobic digesters, which are essentially RCC reactors. The third is the refinery unit, which separates and purifies the gas.\n\n“Bio methane is on par with LPG prices, and in use, it can provide a lot of savings, like, for instance, if the customer is not using it on a cylinder basis, then the pricing is for the amount of gas that is used. There is no wastage like in LPG cylinders. I would say there is about 15 per cent saving with bio methane when you compare it to LPG,” Narayan indicated.\n\nStory continues below this ad\n\nAround 12,000 kg of bio-CNG produced annually at the Koramangala plant for supply to Hotel Empire under a commercial contract in 2023 was estimated by some experts to be equivalent to about 600 LPG cylinders, or roughly 11,000 kg of commercial LPG.\n\nGovernment push and expansion vision\n\nKarnataka Transport Minister Ramalinga Reddy, whose constituency includes the Koramangala waste disposal unit, inaugurated a five-tonne-per-day waste-to-energy processing unit at the plant on March 21.\n\n“Initially, the processing capacity was eight tonnes of garbage per day. Today, we have inaugurated an additional five tonnes, taking the total capacity to 13 tonnes of wet waste being processed daily to produce gas,” Reddy said.\n\n“In Bengaluru, at least 2,500 to 3,000 tonnes of wet waste is generated every day. Most of it is dumped in yards along with dry waste, leading to problems such as foul smells, mosquito breeding, and contamination of water sources. If we properly utilise wet waste like this, about half of the city’s waste can be managed efficiently,” he said.\n\nStory continues below this ad\n\n“If we replicate this model in two or three locations in every Assembly constituency in Bengaluru, the city will not face a waste problem at all,” Reddy said.'},
 {'url': 'https://www.bhaskarenglish.in/local/mp/news/mp-lpg-shortage-hotels-restaurants-hit-additional-chief-secretary-rashmi-shami-137506896.html',
  'text': "English News\n\nLocal\n\nMp\n\nMP LPG Shortage Hits Hotels, Restaurants | ACS Rashmi Shami Meets Operators\n\nMP faces LPG shortage, hotels, restaurants hit for 12 days: Operators present concerns to Additional Chief Secretary; decision expected tomorrow\n\nBhopal 3 days ago\n\n\n\nCopy link\n\nHotel and Restaurant Association met Principal Secretary Rashmi Sharma on Sunday and raised demand for cylinder supply.\n\nThe LPG crisis continues in Madhya Pradesh. Hotels and restaurants have not received commercial cylinder supply for 12 consecutive days.\n\nRegarding this, on Sunday, the National Restaurant Association of India Madhya Pradesh Chapter and Federation of Hotel and Restaurant Association of India met with Additional Chief Secretary of Food and Civil Supplies Department, Rashmi Shami.\n\nChief Secretary Shami spoke with operators on the holiday and also held a meeting with oil companies.\n\nIt should be noted that while the oil companies' new guidelines mention providing 10% commercial cylinders, supply orders have not been issued. Due to this, more than 50 thousand hotels and restaurants in the state are under crisis. They are on the verge of closing down.\n\nBhopal Hotel and Restaurant Association President Tejkulpal Singh Pali said that the hotel business is on the verge of shutdown due to strict restrictions on commercial gas supply. Solutions were discussed regarding this. Demands were made to restore an uninterrupted gas supply, and a memorandum was submitted.\n\nNRAI representative Abhishek Baheti said that difficulties have increased due to the non-availability of commercial gas. In the absence of gas, hotel and restaurant operators are facing a major crisis. Demands have been made to resolve this issue.\n\nThere are more than 2000 hotels and restaurants in Bhopal. Demand has been made to provide cylinders soon.\n\nProblems in 2000 hotels in Bhopal Association President Pali said that hotels, restaurants, dhabas, food services, etc., in Bhopal play an important role in job creation and the local economy, but they are facing major operational difficulties due to a lack of commercial LPG cylinders.\n\nThey have demanded that a limited quota of commercial LPG cylinders be allocated to registered hotels and restaurants in Bhopal based on their actual operational requirements.\n\nEach establishment should be supplied with commercial LPG cylinders to maintain necessary kitchen operations and avoid disruption in food services. There are 2,000 hotels and restaurants in Bhopal where the situation has become serious.\n\nCentral Government's orders are not being implemented Madhya Pradesh Hotel and Restaurant Association President Sumit Suri said that representatives of hotel organizations across the state claim that despite the Center's supply order, no clear guidelines have been issued by the state government yet. Due to this, the local distribution system has come to a standstill.\n\nSuri said that we have placed our demands before the government and we hope that help will reach us as soon as possible. Millions of people's employment is connected to the Hotel and Restaurant Association. Everyone is facing a crisis of livelihood.\n\nSame rules for all hotels not right According to President Suri, the organization's main demand is to increase the current 20 percent limit to 50 percent so that businesses can operate smoothly. Additionally, they have put forward a new proposal that there should not be uniform supply rules for all establishments.\n\nThe gas quota should be determined based on the category of hotels and their demand. Larger establishments should be provided more gas according to their consumption, and smaller establishments should be provided with gas in proportion to their needs. Along with this, there is also a demand to increase the PNG supply according to requirements.\n\nThese officials were present NRAI representative Baheti said that the Principal Secretary has assured to provide gas to hotels and restaurants. He has also promised to take an appropriate decision by Monday.\n\nThe delegation included Sachin Agarwal, Deepesh Motwani, Shrikant Singh, Amit Baheti, Garvit Agarwal, Sagar Gaire, Vishnu Sharma, Kush Manohar, Sapan Arora, Dinesh Dawar, Jastej Pali, and others were also present."},
 {'url': 'https://thenewsmill.com/2026/03/commercial-lpg-shortage-disrupts-hotels-as-government-prioritises-domestic-supply-amid-west-asia-conflict/',

In [91]:
df = pd.DataFrame({'url':[a1['url'] for a1 in articles], 'preview':[a1['text'][:500] for a1 in articles]})
df

,url,preview
0,https://indianexpress.com/article/cities/banga...,Even as many restaurants in Bengaluru cut thei...
1,https://www.bhaskarenglish.in/local/mp/news/mp...,English News\n\nLocal\n\nMp\n\nMP LPG Shortage...
2,https://thenewsmill.com/2026/03/commercial-lpg...,A shortage of commercial LPG is affecting hote...
3,https://www.thegoan.net/goa-news/%EF%BB%BFlpg-...,PANAJI: A deepening shortage of commercial LPG...
4,https://economictimes.indiatimes.com/industry/...,Live Events\n\n\n\nas a Reliable and Trusted N...
...,...,...
80,https://www.telegraphindia.com/business/lpg-cr...,Opposition leaders targeted the government of ...
81,https://thesouthfirst.com/tamilnadu/lpg-shorta...,"LPG shortage hits Tamil Nadu: Hotels struggle,..."
82,https://www.millenniumpost.in/bengal/lpg-crisi...,Siliguri: The impact of the ongoing war in Wes...
83,https://www.thehindu.com/news/cities/bangalore...,“This is the first time I have faced such a si...
84,https://www.newindianexpress.com/cities/thiruv...,THIRUVANANTHAPURAM: A supply crunch of commerc...

In [92]:
df.to_excel(r'C:\Users\amolr\OneDrive\Desktop\News_Article\news_article.xlsx')

In [7]:
l1 = ['https://www.iaanexpress.com/2026/03/11/lpg-crisis-hotels-restaurants-india-2026/',
'https://www.businesstoday.in/india/story/commercial-lpg-shortage-in-india-whats-causing-it-impact-on-hotels-restaurants-households-and-more-520050-2026-03-11',
'https://news-nest.com/2026/03/19/why-india-faces-an-lpg-shortage-despite-hosting-the-worlds-largest-refinery/',
'https://www.goodreturns.in/news/lpg-supply-shortage-in-india-will-10-kg-cylinders-replace-14-2-kg-heres-all-the-details-1497759.html',
'https://hospibuz.com/home-interviews/hotels-opinion/shortage-of-commercial-lpg-_-fhrai-hotel-and-restaurant-association-western-india-hrawi-11191322',
'https://www.indiatvnews.com/news/india/lpg-cylinder-shortage-hits-restaurants-hotels-in-mumbai-kolkata-and-bengaluru-govt-responds-2026-03-10-1033213',
'https://www.npr.org/2026/03/19/nx-s1-5749316/war-fueled-cooking-gas-shortage-hits-households-restaurants-and-factories-in-india',
'https://www.cnn.com/2026/03/18/india/india-lpg-gas-impacts-restaurants-cooking-intl-hnk',
'https://www.cnbc.com/2026/03/10/-iran-war-lpg-disruption-india-restaurants.html',
'https://www.theweek.in/news/biz-tech/2026/03/23/mumbai-restaurant-lpg-shortage.html',]

In [8]:
from newspaper import Article
d = []
a=85
for u in l1:
    article = Article(u)
    article.download()
    article.parse()
    article.text
    file_content = article.text
    a=a+1

    d.append(
        {'a':a,
         'url':u,
         'preview':article.text[:500]

        }
    )


    file_path = fr"C:\Users\amolr\OneDrive\Desktop\News_Article\news\output{a}.txt"
    with open(file_path, "w") as text_file:
        text_file.write(file_content)

In [10]:
import pandas as pd
df1 = pd.DataFrame(d)

In [11]:
df1

,a,url,preview
0,86,https://www.iaanexpress.com/2026/03/11/lpg-cri...,A sudden commercial LPG shortage has thrown In...
1,87,https://www.businesstoday.in/india/story/comme...,"Several cities across India, including Delhi, ..."
2,88,https://news-nest.com/2026/03/19/why-india-fac...,India is grappling with a significant shortage...
3,89,https://www.goodreturns.in/news/lpg-supply-sho...,LPG supply crisis has hit India due to disrupt...
4,90,https://hospibuz.com/home-interviews/hotels-op...,"Mumbai, March 10, 2026:\n\n“The shortage of co..."
5,91,https://www.indiatvnews.com/news/india/lpg-cyl...,Bengaluru:\n\nA sudden crisis of commercial LP...
6,92,https://www.npr.org/2026/03/19/nx-s1-5749316/w...,War-fueled cooking gas shortage hits household...
7,93,https://www.cnn.com/2026/03/18/india/india-lpg...,Iran’s chokehold on the Strait of Hormuz has s...
8,94,https://www.cnbc.com/2026/03/10/-iran-war-lpg-...,Workers prepare butter chicken at Daryaganj re...
9,95,https://www.theweek.in/news/biz-tech/2026/03/2...,The closure of the Middle East airspace eventu...